# -*- coding: utf-8 -*-
# SEO S1: Booking.com auto-reply post — new title/desc + 12 copy-paste reply templates per language.
# Pure data. Plain text only (no HTML); variable parts in [square brackets].

TEMPLATES = {
 "en": {
  "title": "Booking.com Auto-Reply: 3 Methods + 12 Free Templates (2026)",
  "desc": "Auto-reply to Booking.com messages in 2026: 3 methods (templates, scheduled messages, AI) plus 12 free copy-paste templates for common guest questions.",
  "answer_add": "Below you'll find 12 free reply templates you can copy straight into the extranet.",
  "h2": "12 free Booking.com reply templates to copy",
  "intro": "Save each one as a message template in the Booking.com extranet inbox, replace the parts in [brackets] with your hotel's details, and keep replies short and specific.",
  "items": [
   ("Booking confirmation and thank-you", "Dear [Guest name], thank you for booking with [hotel name]. We have received your reservation for [dates] and look forward to welcoming you. If you have any questions before your stay, just reply to this message."),
   ("Pre-arrival information", "Dear [Guest name], we look forward to seeing you on [date]. Our address is [address], and the easiest way to reach us is [directions]. Could you let us know your approximate arrival time so we can be ready for you?"),
   ("Check-in time and early check-in", "Dear [Guest name], check-in starts at [14:00]. If you arrive earlier, we will do our best to have your room ready as soon as possible, depending on occupancy that day, and you are welcome to leave your luggage with us in the meantime. Please let us know your expected arrival time."),
   ("Late check-out request", "Dear [Guest name], our standard check-out time is [11:00]. Depending on occupancy, a late check-out until [time] may be possible, and we will confirm it the day before your departure. If it is available, the fee is [price]."),
   ("Late or after-hours arrival", "Dear [Guest name], thank you for letting us know. Our reception is open until [time]; for later arrivals, [describe late check-in: night staff, key box or door code sent on the day]. Please send us your estimated arrival time so we can have everything ready."),
   ("Parking", "Dear [Guest name], we have [on-site / nearby] parking at [address]. It costs [price] per day, and spaces are [subject to availability / bookable in advance]. If you are coming by car, let us know and we will note it on your booking."),
   ("Airport transfer request", "Dear [Guest name], we would be happy to arrange a transfer from [airport] to the hotel. The cost is [price] for [number] people. Please send us your flight number and arrival time, and we will confirm the transfer with you."),
   ("Breakfast", "Dear [Guest name], breakfast is served from [07:00] to [10:30] in [location]. Your Booking.com confirmation shows whether breakfast is included in your rate. If it isn't, you can add it at the hotel for [price] per person per day."),
   ("Luggage storage", "Dear [Guest name], of course, you are welcome to leave your luggage with us before check-in or after check-out [free of charge]. Just ask at reception and we will store it safely for you."),
   ("Pets", "Dear [Guest name], thank you for asking in advance. Pets [are / are not] allowed at our property, as stated in the house rules on our Booking.com page. Where pets are allowed, a fee of [price] per night applies; could you tell us the type and size of your pet so we can prepare a suitable room?"),
   ("Invoice request", "Dear [Guest name], we will be happy to issue an invoice for your stay. Please send us the company name, tax ID and full billing address, and we will have the invoice ready [at check-out / by email after your stay]."),
   ("Date change or cancellation", "Dear [Guest name], the conditions for changes and cancellations depend on the policy of your booking, which you can find in your Booking.com confirmation. You can request a date change or cancellation directly in the Booking.com app or under 'Manage booking'. If you send us your new dates, we will gladly check availability for you."),
  ],
  "note": "Keep payments inside Booking.com: don't send payment links or personal contact details in messages, and make sure your templates match the house rules and policies on your listing.",
  "faq": ("Where do I save reply templates in Booking.com?", "In the Booking.com extranet, open the guest messages inbox and save each text as a message template. When you reply, pick the template and fill in the parts in brackets before sending."),
 },
 "tr": {
  "title": "Booking.com Mesajlarına Otomatik Cevap: 12 Ücretsiz Şablon (2026)",
  "desc": "Booking.com mesajlarına otomatik cevap için 3 yöntem: şablon, planlı mesaj ve AI asistanı. Kopyalayıp kullanabileceğiniz 12 ücretsiz şablon (2026).",
  "answer_add": "Aşağıda extranet'e doğrudan kopyalayabileceğiniz 12 ücretsiz cevap şablonu bulabilirsiniz.",
  "h2": "Kopyalayıp kullanabileceğiniz 12 ücretsiz Booking.com cevap şablonu",
  "intro": "Her birini Booking.com extranet'indeki mesaj kutusunda şablon olarak kaydedin, [köşeli parantez] içindeki yerleri kendi otel bilgilerinizle değiştirin ve cevapları kısa tutun.",
  "items": [
   ("Rezervasyon sonrası teşekkür", "Sayın [Misafir adı], [otel adı] olarak bizi tercih ettiğiniz için teşekkür ederiz. [Tarihler] için rezervasyonunuz elimize ulaştı ve sizi ağırlamayı dört gözle bekliyoruz. Konaklamanızdan önce bir sorunuz olursa bu mesaja cevap yazmanız yeterli."),
   ("Varış öncesi bilgi", "Sayın [Misafir adı], [tarih] tarihinde sizi ağırlamayı bekliyoruz. Adresimiz [adres]; bize en kolay [ulaşım tarifi] ile ulaşabilirsiniz. Hazırlıklarımızı yapabilmemiz için tahmini varış saatinizi paylaşabilir misiniz?"),
   ("Check-in saati ve erken giriş", "Sayın [Misafir adı], check-in [14:00] itibarıyla başlıyor. Daha erken gelirseniz, o günkü doluluğa göre odanızı mümkün olan en kısa sürede hazırlamaya çalışırız; bu arada bavullarınızı bize bırakabilirsiniz. Tahmini varış saatinizi bildirirseniz seviniriz."),
   ("Geç çıkış talebi", "Sayın [Misafir adı], standart check-out saatimiz [11:00]. Doluluğa bağlı olarak [saat] saatine kadar geç çıkış mümkün olabilir; bunu ayrılışınızdan bir gün önce netleştiririz. Uygun olursa geç çıkış ücreti [fiyat] olacaktır."),
   ("Geç saatte varış", "Sayın [Misafir adı], bilgi verdiğiniz için teşekkür ederiz. Resepsiyonumuz [saat] saatine kadar açık; daha geç varışlarda [geç giriş bilgisi: gece görevlisi, anahtar kutusu veya o gün gönderilecek giriş kodu]. Her şeyi hazır edebilmemiz için tahmini varış saatinizi bize iletir misiniz?"),
   ("Otopark", "Sayın [Misafir adı], [otelde / otele yakın] otoparkımız var; adresi [adres]. Günlük ücreti [fiyat], yerler ise [müsaitliğe bağlıdır / önceden ayrılabilir]. Araçla gelecekseniz bize haber verin, rezervasyonunuza not alalım."),
   ("Havalimanı transferi", "Sayın [Misafir adı], [havalimanı] ile otelimiz arasında transferinizi memnuniyetle ayarlayabiliriz. [Kişi sayısı] kişi için ücret [fiyat]. Uçuş numaranızı ve iniş saatinizi gönderirseniz transferi sizinle teyit ederiz."),
   ("Kahvaltı", "Sayın [Misafir adı], kahvaltımız [07:00] ile [10:30] arasında [yer] bölümünde servis ediliyor. Kahvaltının fiyata dahil olup olmadığını Booking.com onayınızda görebilirsiniz. Dahil değilse, otelde kişi başı günlük [fiyat] karşılığında ekleyebilirsiniz."),
   ("Bavul emaneti", "Sayın [Misafir adı], elbette; check-in öncesinde veya check-out sonrasında bavullarınızı [ücretsiz olarak] bizde bırakabilirsiniz. Resepsiyona söylemeniz yeterli, eşyalarınızı güvenle saklarız."),
   ("Evcil hayvan", "Sayın [Misafir adı], önceden sorduğunuz için teşekkür ederiz. Tesisimizde evcil hayvan [kabul edilmektedir / kabul edilmemektedir]; bu kural Booking.com sayfamızdaki ev kurallarıyla aynıdır. Kabul edildiği durumlarda gecelik [fiyat] ücret uygulanır; size uygun odayı hazırlayabilmemiz için hayvanınızın türünü ve büyüklüğünü paylaşır mısınız?"),
   ("Fatura talebi", "Sayın [Misafir adı], konaklamanız için memnuniyetle fatura düzenleriz. Lütfen şirket unvanını, vergi dairesi ve vergi numarasını ve fatura adresini bize iletin; faturanızı [çıkışta / konaklamanızdan sonra e-postayla] hazırlayalım."),
   ("Tarih değişikliği / iptal", "Sayın [Misafir adı], değişiklik ve iptal koşulları rezervasyonunuzun iptal politikasına bağlıdır; bu bilgiyi Booking.com onayınızda bulabilirsiniz. Tarih değişikliği veya iptal talebinizi doğrudan Booking.com uygulamasından ya da 'Rezervasyonu yönet' bölümünden iletebilirsiniz. Yeni tarihlerinizi yazarsanız müsaitliği sizin için memnuniyetle kontrol ederiz."),
  ],
  "note": "Ödemeyi Booking.com üzerinde tutun: mesajlarda ödeme linki veya kişisel iletişim bilgisi paylaşmayın, şablonlarınızdaki kuralların ilanınızdaki ev kurallarıyla aynı olduğundan emin olun.",
  "faq": ("Booking.com cevap şablonları nereye kaydedilir?", "Booking.com extranet'inde misafir mesajları kutusunu açıp her metni mesaj şablonu olarak kaydedin. Cevap yazarken şablonu seçip köşeli parantez içindeki yerleri doldurmanız yeterli."),
 },
 "es": {
  "title": "Respuesta automática Booking.com: 12 plantillas gratis (2026)",
  "desc": "Cómo automatizar los mensajes de Booking.com en 2026: 3 métodos (plantillas, mensajes programados e IA) y 12 plantillas gratis para copiar y pegar.",
  "answer_add": "Más abajo tienes 12 plantillas de respuesta gratuitas para copiar en la extranet.",
  "h2": "12 plantillas gratis para responder mensajes de Booking.com",
  "intro": "Guárdalas como plantillas de mensaje en la bandeja de entrada de la extranet de Booking.com, sustituye las partes entre [corchetes] por los datos de tu hotel y mantén las respuestas breves.",
  "items": [
   ("Confirmación y agradecimiento", "Hola, [Nombre]: muchas gracias por reservar en [nombre del hotel]. Hemos recibido su reserva para [fechas] y estaremos encantados de recibirle. Si tiene cualquier pregunta antes de su estancia, solo tiene que responder a este mensaje."),
   ("Información antes de la llegada", "Hola, [Nombre]: le esperamos el [fecha]. Nuestra dirección es [dirección] y la forma más fácil de llegar es [indicaciones]. ¿Podría indicarnos su hora aproximada de llegada para tenerlo todo preparado?"),
   ("Hora de check-in y llegada anticipada", "Hola, [Nombre]: el check-in es a partir de las [14:00]. Si llega antes, intentaremos tener su habitación lista lo antes posible según la ocupación de ese día, y mientras tanto puede dejarnos su equipaje. Le agradeceríamos que nos indicara su hora prevista de llegada."),
   ("Salida tardía", "Hola, [Nombre]: la hora de salida habitual es a las [11:00]. Según la ocupación, podría ser posible dejar la habitación más tarde, hasta las [hora]; se lo confirmaremos el día antes de su salida. Si hay disponibilidad, el suplemento es de [precio]."),
   ("Llegada tarde o fuera de horario", "Hola, [Nombre]: gracias por avisarnos. Nuestra recepción está abierta hasta las [hora]; para llegadas posteriores, [explicar el check-in nocturno: personal de noche, caja de llaves o código de acceso que enviaremos ese día]. ¿Nos podría indicar su hora estimada de llegada para dejarlo todo preparado?"),
   ("Aparcamiento", "Hola, [Nombre]: disponemos de aparcamiento [en el hotel / cerca del hotel] en [dirección]. El precio es de [precio] al día y las plazas están [sujetas a disponibilidad / disponibles con reserva previa]. Si viene en coche, avísenos y lo anotaremos en su reserva."),
   ("Traslado desde el aeropuerto", "Hola, [Nombre]: con mucho gusto podemos organizar su traslado desde [aeropuerto] hasta el hotel. El precio es de [precio] para [número] personas. Envíenos su número de vuelo y la hora de llegada y le confirmaremos el servicio."),
   ("Desayuno", "Hola, [Nombre]: el desayuno se sirve de [07:00] a [10:30] en [lugar]. En la confirmación de Booking.com puede ver si está incluido en su tarifa. Si no lo está, puede añadirlo en el hotel por [precio] por persona y día."),
   ("Consigna de equipaje", "Hola, [Nombre]: por supuesto, puede dejarnos su equipaje antes del check-in o después del check-out [sin coste]. Solo tiene que pedirlo en recepción y lo guardaremos en un lugar seguro."),
   ("Mascotas", "Hola, [Nombre]: gracias por consultarlo con antelación. En nuestro alojamiento [se admiten / no se admiten] mascotas, tal como indican las normas de la casa en nuestra página de Booking.com. Cuando se admiten, se aplica un suplemento de [precio] por noche; ¿nos indica qué animal es y su tamaño para prepararle la habitación adecuada?"),
   ("Solicitud de factura", "Hola, [Nombre]: con mucho gusto le emitiremos una factura de su estancia. Envíenos la razón social, el NIF y la dirección fiscal completa, y la tendremos lista [a la salida / por correo electrónico después de su estancia]."),
   ("Cambio de fechas o cancelación", "Hola, [Nombre]: las condiciones de cambio y cancelación dependen de la política de su reserva, que encontrará en la confirmación de Booking.com. Puede solicitar el cambio de fechas o la cancelación directamente desde la app de Booking.com o en 'Gestionar reserva'. Si nos indica las nuevas fechas, comprobaremos encantados la disponibilidad."),
  ],
  "note": "Mantén los pagos dentro de Booking.com: no envíes enlaces de pago ni datos de contacto personales por mensaje, y asegúrate de que tus plantillas coinciden con las normas de la casa de tu alojamiento en Booking.com.",
  "faq": ("¿Dónde se guardan las plantillas de respuesta en Booking.com?", "En la extranet de Booking.com, abre la bandeja de mensajes de los huéspedes y guarda cada texto como plantilla de mensaje. Al responder, elige la plantilla y completa las partes entre corchetes."),
 },
 "it": {
  "title": "Risposta automatica Booking.com: 12 modelli gratuiti (2026)",
  "desc": "Rispondere in automatico ai messaggi di Booking.com nel 2026: 3 metodi (modelli, messaggi programmati, AI) e 12 modelli gratuiti da copiare e incollare.",
  "answer_add": "Qui sotto trovi 12 modelli di risposta gratuiti da copiare nell'extranet.",
  "h2": "12 modelli di risposta Booking.com gratuiti da copiare",
  "intro": "Salvali come modelli di messaggio nella casella dell'extranet di Booking.com, sostituisci le parti tra [parentesi quadre] con i dati della tua struttura e mantieni le risposte brevi.",
  "items": [
   ("Conferma e ringraziamento", "Gentile [Nome], grazie per aver prenotato presso [nome hotel]. Abbiamo ricevuto la Sua prenotazione per [date] e saremo lieti di accoglierLa. Per qualsiasi domanda prima del soggiorno, può rispondere direttamente a questo messaggio."),
   ("Informazioni prima dell'arrivo", "Gentile [Nome], La aspettiamo il [data]. Il nostro indirizzo è [indirizzo] e il modo più semplice per raggiungerci è [indicazioni]. Potrebbe comunicarci l'orario di arrivo previsto, così da farci trovare pronti?"),
   ("Orario di check-in e arrivo anticipato", "Gentile [Nome], il check-in è disponibile dalle [14:00]. Se arriva prima, cercheremo di preparare la camera il prima possibile in base all'occupazione del giorno; nel frattempo può lasciare i bagagli da noi. Ci farebbe piacere conoscere il Suo orario di arrivo previsto."),
   ("Late check-out", "Gentile [Nome], il check-out è previsto entro le [11:00]. In base all'occupazione potrebbe essere possibile lasciare la camera più tardi, fino alle [ora]; glielo confermeremo il giorno prima della partenza. Se disponibile, il supplemento è di [prezzo]."),
   ("Arrivo in tarda serata", "Gentile [Nome], grazie per averci avvisato. La reception è aperta fino alle [ora]; per gli arrivi successivi [descrivere il check-in notturno: portiere di notte, cassetta delle chiavi o codice d'accesso inviato il giorno stesso]. Ci può indicare l'orario di arrivo previsto, così da preparare tutto?"),
   ("Parcheggio", "Gentile [Nome], disponiamo di un parcheggio [in struttura / nelle vicinanze] in [indirizzo]. Il costo è di [prezzo] al giorno e i posti sono [soggetti a disponibilità / prenotabili in anticipo]. Se arriva in auto, ce lo comunichi e lo annoteremo sulla Sua prenotazione."),
   ("Transfer dall'aeroporto", "Gentile [Nome], saremo lieti di organizzare il transfer da [aeroporto] all'hotel. Il costo è di [prezzo] per [numero] persone. Ci invii il numero del volo e l'orario di arrivo e Le confermeremo il servizio."),
   ("Colazione", "Gentile [Nome], la colazione viene servita dalle [07:00] alle [10:30] in [luogo]. Nella conferma di Booking.com può verificare se è inclusa nella Sua tariffa. In caso contrario, può aggiungerla in hotel a [prezzo] a persona al giorno."),
   ("Deposito bagagli", "Gentile [Nome], certamente: può lasciare i bagagli da noi prima del check-in o dopo il check-out [senza costi aggiuntivi]. Basta chiedere alla reception e li custodiremo in un luogo sicuro."),
   ("Animali domestici", "Gentile [Nome], grazie per averlo chiesto in anticipo. Nella nostra struttura gli animali [sono ammessi / non sono ammessi], come indicato nelle regole della casa sulla nostra pagina Booking.com. Quando sono ammessi, è previsto un supplemento di [prezzo] a notte; ci può indicare tipo e taglia dell'animale per preparare la camera più adatta?"),
   ("Richiesta di fattura", "Gentile [Nome], saremo lieti di emettere la fattura per il Suo soggiorno. Ci invii la ragione sociale, la partita IVA, l'indirizzo della sede e, se disponibile, il codice destinatario SDI o la PEC. Prepareremo la fattura [al check-out / dopo il soggiorno]."),
   ("Modifica delle date o cancellazione", "Gentile [Nome], le condizioni di modifica e cancellazione dipendono dalla politica della Sua prenotazione, indicata nella conferma di Booking.com. Può richiedere il cambio di date o la cancellazione direttamente dall'app di Booking.com o dalla sezione 'Gestisci prenotazione'. Se ci indica le nuove date, verificheremo volentieri la disponibilità."),
  ],
  "note": "Mantieni i pagamenti all'interno di Booking.com: non inviare link di pagamento né contatti personali nei messaggi e verifica che i modelli rispecchino le regole della casa del tuo annuncio.",
  "faq": ("Dove si salvano i modelli di risposta su Booking.com?", "Nell'extranet di Booking.com apri la casella dei messaggi degli ospiti e salva ogni testo come modello di messaggio. Quando rispondi, scegli il modello e completa le parti tra parentesi quadre."),
 },
 "pt": {
  "title": "Resposta automática Booking.com: 12 modelos grátis (2026)",
  "desc": "Como responder automaticamente às mensagens do Booking.com em 2026: 3 métodos (modelos, mensagens programadas e IA) e 12 modelos grátis para copiar.",
  "answer_add": "Logo abaixo você encontra 12 modelos de resposta grátis para copiar na extranet.",
  "h2": "12 modelos grátis de resposta para o Booking.com",
  "intro": "Salve cada um como modelo de mensagem na caixa de entrada da extranet do Booking.com, troque as partes entre [colchetes] pelos dados do seu hotel e mantenha as respostas curtas.",
  "items": [
   ("Confirmação e agradecimento", "Olá, [Nome]! Obrigado por reservar no [nome do hotel]. Recebemos sua reserva para [datas] e vamos adorar receber você. Se tiver qualquer dúvida antes da hospedagem, é só responder esta mensagem."),
   ("Informações antes da chegada", "Olá, [Nome]! Estamos esperando você no dia [data]. Nosso endereço é [endereço] e o jeito mais fácil de chegar é [como chegar]. Você pode nos informar o horário aproximado de chegada para deixarmos tudo pronto?"),
   ("Horário de check-in e check-in antecipado", "Olá, [Nome]! O check-in é a partir das [14:00]. Se você chegar antes, vamos tentar liberar o quarto o quanto antes, de acordo com a ocupação do dia, e enquanto isso você pode deixar a bagagem conosco. Pode nos dizer o horário previsto de chegada?"),
   ("Check-out tardio", "Olá, [Nome]! Nosso check-out padrão é até as [11:00]. Dependendo da ocupação, pode ser possível sair mais tarde, até as [horário]; confirmamos com você na véspera da saída. Se houver disponibilidade, a taxa é de [preço]."),
   ("Chegada tarde da noite", "Olá, [Nome]! Obrigado por avisar. Nossa recepção funciona até as [horário]; para chegadas depois disso, [explicar o check-in noturno: porteiro noturno, cofre de chaves ou código de acesso enviado no dia]. Pode nos passar o horário estimado de chegada para deixarmos tudo preparado?"),
   ("Estacionamento", "Olá, [Nome]! Temos estacionamento [no hotel / perto do hotel] em [endereço]. A diária do estacionamento é de [preço] e as vagas são [sujeitas à disponibilidade / reserváveis com antecedência]. Se vier de carro, é só avisar que anotamos na sua reserva."),
   ("Transfer do aeroporto", "Olá, [Nome]! Podemos organizar com prazer o transfer do [aeroporto] até o hotel. O valor é de [preço] para [número] pessoas. Envie o número do voo e o horário de chegada que confirmamos o serviço com você."),
   ("Café da manhã", "Olá, [Nome]! O café da manhã é servido das [07:00] às [10:30] no [local]. Na confirmação do Booking.com você vê se ele está incluído na sua tarifa. Se não estiver, é possível adicioná-lo no hotel por [preço] por pessoa por dia."),
   ("Guarda-volumes", "Olá, [Nome]! Claro, você pode deixar a bagagem conosco antes do check-in ou depois do check-out [sem custo]. É só pedir na recepção que guardamos tudo em local seguro."),
   ("Animais de estimação", "Olá, [Nome]! Obrigado por perguntar com antecedência. Nossa propriedade [aceita / não aceita] animais de estimação, conforme as regras da casa na nossa página do Booking.com. Quando aceitos, cobramos uma taxa de [preço] por noite; pode nos dizer a espécie e o porte do seu pet para prepararmos o quarto mais adequado?"),
   ("Pedido de nota fiscal", "Olá, [Nome]! Emitimos a nota fiscal da sua hospedagem com prazer. Por favor, envie a razão social, o CNPJ e o endereço completo da empresa; deixamos a nota pronta [no check-out / por e-mail após a hospedagem]."),
   ("Alteração de datas ou cancelamento", "Olá, [Nome]! As condições de alteração e cancelamento dependem da política da sua reserva, que aparece na confirmação do Booking.com. Você pode pedir a alteração de datas ou o cancelamento direto pelo app do Booking.com ou em 'Gerenciar reserva'. Se nos informar as novas datas, verificamos a disponibilidade com prazer."),
  ],
  "note": "Mantenha os pagamentos dentro do Booking.com: não envie links de pagamento nem contatos pessoais por mensagem e confira se seus modelos batem com as regras da casa do seu anúncio.",
  "faq": ("Onde salvar modelos de resposta no Booking.com?", "Na extranet do Booking.com, abra a caixa de mensagens dos hóspedes e salve cada texto como modelo de mensagem. Na hora de responder, escolha o modelo e preencha as partes entre colchetes."),
 },
 "fr": {
  "title": "Réponse automatique Booking.com : 12 modèles gratuits (2026)",
  "desc": "Répondre automatiquement aux messages Booking.com en 2026 : 3 méthodes (modèles, messages programmés, IA) et 12 modèles gratuits à copier-coller.",
  "answer_add": "Vous trouverez ci-dessous 12 modèles de réponse gratuits à copier dans l’extranet.",
  "h2": "12 modèles de réponse Booking.com gratuits à copier",
  "intro": "Enregistrez-les comme modèles de message dans la boîte de réception de l’extranet Booking.com, remplacez les parties entre [crochets] par les informations de votre établissement et gardez des réponses courtes.",
  "items": [
   ("Confirmation et remerciement", "Bonjour [Prénom], merci d’avoir réservé à [nom de l’hôtel]. Nous avons bien reçu votre réservation pour [dates] et nous nous réjouissons de vous accueillir. Pour toute question avant votre séjour, il vous suffit de répondre à ce message."),
   ("Informations avant l’arrivée", "Bonjour [Prénom], nous vous attendons le [date]. Notre adresse est [adresse] et le plus simple pour venir est [itinéraire]. Pourriez-vous nous indiquer votre heure d’arrivée approximative afin que tout soit prêt ?"),
   ("Heure d’arrivée et arrivée anticipée", "Bonjour [Prénom], les chambres sont disponibles à partir de [14h00]. Si vous arrivez plus tôt, nous ferons notre possible pour préparer votre chambre au plus vite selon l’occupation du jour, et vous pourrez déposer vos bagages chez nous en attendant. Merci de nous indiquer votre heure d’arrivée prévue."),
   ("Départ tardif", "Bonjour [Prénom], le départ se fait habituellement avant [11h00]. Selon l’occupation, un départ tardif jusqu’à [heure] peut être possible ; nous vous le confirmerons la veille de votre départ. S’il est disponible, le supplément est de [prix]."),
   ("Arrivée tardive", "Bonjour [Prénom], merci de nous avoir prévenus. Notre réception est ouverte jusqu’à [heure] ; pour une arrivée plus tardive, [expliquer l’arrivée de nuit : veilleur de nuit, boîte à clés ou code d’accès envoyé le jour même]. Pourriez-vous nous indiquer votre heure d’arrivée estimée pour que tout soit prêt ?"),
   ("Parking", "Bonjour [Prénom], nous disposons d’un parking [sur place / à proximité] au [adresse]. Il coûte [prix] par jour et les places sont [selon disponibilité / réservables à l’avance]. Si vous venez en voiture, prévenez-nous et nous le noterons sur votre réservation."),
   ("Transfert aéroport", "Bonjour [Prénom], nous pouvons volontiers organiser votre transfert depuis [aéroport] jusqu’à l’hôtel. Le tarif est de [prix] pour [nombre] personnes. Envoyez-nous votre numéro de vol et votre heure d’arrivée, et nous vous confirmerons le service."),
   ("Petit-déjeuner", "Bonjour [Prénom], le petit-déjeuner est servi de [7h00] à [10h30] [lieu]. Votre confirmation Booking.com indique s’il est inclus dans votre tarif. Sinon, vous pouvez l’ajouter sur place pour [prix] par personne et par jour."),
   ("Bagagerie", "Bonjour [Prénom], bien sûr : vous pouvez laisser vos bagages chez nous avant l’arrivée ou après le départ [gratuitement]. Il suffit de le demander à la réception et nous les garderons en lieu sûr."),
   ("Animaux", "Bonjour [Prénom], merci de nous poser la question à l’avance. Les animaux [sont acceptés / ne sont pas acceptés] dans notre établissement, comme indiqué dans le règlement intérieur de notre page Booking.com. Lorsqu’ils sont acceptés, un supplément de [prix] par nuit s’applique ; pourriez-vous nous préciser l’espèce et la taille de votre animal afin que nous préparions une chambre adaptée ?"),
   ("Demande de facture", "Bonjour [Prénom], nous établirons volontiers une facture pour votre séjour. Merci de nous envoyer la raison sociale, le numéro de TVA intracommunautaire ou le SIRET et l’adresse de facturation complète ; nous préparerons la facture [au départ / par e-mail après votre séjour]."),
   ("Changement de dates ou annulation", "Bonjour [Prénom], les conditions de modification et d’annulation dépendent de la politique de votre réservation, indiquée dans votre confirmation Booking.com. Vous pouvez demander un changement de dates ou une annulation directement dans l’application Booking.com ou via « Gérer la réservation ». Si vous nous indiquez vos nouvelles dates, nous vérifierons volontiers les disponibilités."),
  ],
  "note": "Gardez les paiements dans Booking.com : n’envoyez ni lien de paiement ni coordonnées personnelles par message, et vérifiez que vos modèles reprennent bien le règlement intérieur de votre annonce.",
  "faq": ("Où enregistrer des modèles de réponse sur Booking.com ?", "Dans l’extranet Booking.com, ouvrez la boîte de réception des messages clients et enregistrez chaque texte comme modèle de message. Au moment de répondre, choisissez le modèle et complétez les parties entre crochets."),
 },
}
