// Hostlio Pro — lightweight i18n
const I18N = {
  en: {
    nav_features: 'Features', nav_pricing: 'Pricing', nav_demo: 'Demo', nav_dashboard: 'Go to Dashboard', nav_getstarted: 'Get Started',
    hero_badge: 'AI-Powered Hotel Management',
    hero_title_1: 'Your AI-Powered<br>Front Desk.',
    hero_title_2: '24/7, in 30+ Languages.',
    hero_sub: 'Stop losing bookings to unanswered messages. Automate guest communication across Booking.com, Airbnb, Email, Web Chat & Telegram — starting at $49/month.',
    hero_cta_trial: 'Start Free Trial →', hero_cta_demo: 'Watch Demo',
    pain_label: 'Pain Points', pain_title: 'Sound familiar?', pain_sub: 'Every independent hotel owner knows these problems. We built Hostlio Pro to solve them all.',
    pain_1: '"Guests message at 3am. You miss it. They book elsewhere."', pain_2: '"5 platforms. 5 logins. Hours wasted every single day."', pain_3: '"One wrong click. Double booking. Angry guests."', pain_4: '"Low season hits hard. No tools to fill empty rooms."',
    feat_label: 'Features', feat_title: "Everything your hotel needs.<br>Nothing you don't.", feat_sub: 'One beautifully simple platform that replaces five different tools.',
    feat_1_t: 'AI Guest Messaging', feat_1_d: 'Replies in 30+ languages across OTAs, Email, Web Chat & Telegram. 24/7 — without lifting a finger.',
    feat_2_t: 'Room Rack Calendar', feat_2_d: 'Drag & drop reservations. See every room at a glance.',
    feat_3_t: '100+ OTA Integration', feat_3_d: 'Booking.com, Airbnb, Expedia, Agoda, Trip.com and 100+ more via Channex. Real-time sync. Zero overbooking.',
    feat_4_t: 'PDF Visa Forms', feat_4_d: 'Auto-generate with your hotel logo. Share instantly upon check-in.',
    feat_5_t: 'Transfer & Tours', feat_5_d: 'Sell airport transfers to guests automatically. Extra revenue, zero effort.',
    feat_6_t: 'Mobile App', feat_6_d: 'Manage your hotel offline. Works without internet. Always in your pocket.',
    how_label: 'How It Works', how_title: 'Up and running in 30 minutes', how_sub: 'No IT team required. No complex setup. Just four simple steps.',
    how_1_t: 'Connect your channels', how_1_d: 'Link Booking.com, Airbnb, Expedia and 100+ more with one click. Your reservations import automatically.',
    how_2_t: 'AI handles messages', how_2_d: 'Your AI assistant replies to every guest — in their language — day and night. You review, never repeat.',
    how_3_t: 'Manage from one dashboard', how_3_d: 'See all rooms, all channels, all messages in one beautiful place. Take back 3+ hours every day.',
    how_4_t: 'Grow your revenue', how_4_d: 'Offer airport transfers, tours and upsells automatically. Your AI suggests extras to every guest — turning bookings into bigger bookings.',
    price_label: 'Pricing', price_title: 'Simple, transparent pricing', price_sub: 'No hidden fees. No long-term contracts. Cancel anytime.',
    comp_label: 'Comparison', comp_title: 'Why hotels choose Hostlio Pro', comp_sub: 'See how we stack up against legacy hotel software.',
    cta_title: 'Ready to automate your hotel?',
    banner_earlybird: '🔥 Early Bird Deal — Limited to the next 50 customers: 20% off all plans!',
    trust_worldwide: 'Trusted by independent hotels worldwide', trust_label: 'Trusted by independent hotels in 20+ countries — syncs with',
    plan_cta: 'Start Free Trial', plan_cta_arrow: 'Start Free Trial →',
    cta_sub: 'Join independent hotels saving 3+ hours every day with Hostlio Pro.', cta_btn: 'Start Free Trial →',
    foot_product: 'Product', foot_company: 'Company', foot_legal: 'Legal', foot_how: 'How it Works', foot_compare: 'Compare', foot_about: 'About', foot_contact: 'Contact',
    stat_countries: '20+ Countries', stat_sync: '100+ Channel Sync', stat_overbook: 'Zero overbooking guaranteed',
    f_1prop: '1 property', f_10rooms: 'Up to 10 rooms', f_5kmsg: '5,000 AI messages/month', f_otaemail: 'OTA + Email messaging', f_roomrack: 'Room Rack Calendar', f_pdfvisa: 'PDF Visa Forms',
    f_50rooms: 'Up to 50 rooms', f_20kmsg: '20,000 AI messages/month', f_allchan: 'All channels (100+ OTAs)', f_allmsg: 'OTA + Email + Web Chat + Telegram', f_transfer: 'Transfer & Tour sales', f_mobile: 'Mobile App',
    f_multiprop: 'Multi-property', f_150rooms: 'Up to 150 rooms', f_50kmsg: '50,000 AI messages/month', f_prioritysync: 'All 100+ channels + priority sync', f_prioritysup: 'Priority support (2hr response)', f_onboarding: 'Custom onboarding call', f_whitelabel: 'White-label options',
    plan_note: '14-day free trial',
    ent_name: 'ENTERPRISE', ent_price: 'Custom Pricing', ent_desc: 'For large properties and hotel groups.',
    ent_1: '✓ 150+ rooms', ent_2: '✓ Unlimited AI messages', ent_3: '✓ Everything in Growth', ent_4: '✓ Dedicated account manager', ent_5: '✓ Custom integrations', ent_6: '✓ SLA guarantee', ent_cta: 'Contact Us →',
    comp_feature: 'Feature', comp_r1: 'AI guest messaging automation', comp_r2: '30+ language AI replies', comp_r4: 'Visual room rack calendar', comp_r6: 'Offline mobile app', comp_price: 'Starting price',
    cta_trial: '14-day free trial', cta_cancel: 'Cancel anytime',
    foot_desc: 'AI-powered hotel management for independent hotels worldwide.',
    earlybird: '🔥 Early Bird', comp_expensive: 'expensive at scale',
    comp_r3: '100+ OTA integration', comp_r5: 'Transfer & tour sales', comp_r7: 'PDF visa forms (auto)', comp_perlisting: 'Per-listing',
    faq_back: '← Back to home', faq_title: 'Frequently Asked Questions', faq_sub: "Everything you need to know about Hostlio Pro. Can't find an answer?", faq_contact: 'Contact us', faq_cta: 'Start Free Trial →',
    faq_q1: 'What is Hostlio Pro?', faq_a1: 'Hostlio Pro is an AI-powered hotel management platform for independent hotels, boutique B&Bs, and hostels. It automates guest messaging in 30+ languages, syncs your availability across 100+ OTA channels via Channex, and gives you a single dashboard to run your property.',
    faq_q2: 'How long does setup take?', faq_a2: 'Most hotels are up and running in about 30 minutes. You connect your channels, import your rooms and reservations, and configure your AI assistant — no IT team required.',
    faq_q3: 'Which booking channels do you support?', faq_a3: 'Through our Channex integration, Hostlio Pro connects to 100+ OTAs including Booking.com, Airbnb, Expedia, Agoda, and Trip.com. Availability and rates sync in real time to prevent overbookings. See our <a href="/channels.html" style="color:var(--orange);font-weight:600">full channel list</a>.',
    faq_q4: 'What languages does the AI support?', faq_a4: "The AI assistant replies to guests in 30+ languages automatically — it detects the guest's language and responds naturally, 24/7, with no extra effort from you.",
    faq_q5: 'Which messaging channels are supported?', faq_a5: 'Hostlio Pro handles guest messages across OTA inboxes (Booking.com, Airbnb), Email, your website chat widget, and Telegram. More channels are added regularly.',
    faq_q6: 'How much does it cost?', faq_a6: 'Plans start at $49/month (Starter, normally $59) for up to 10 rooms. Pro ($89/mo) adds all channels plus transfer & tour upsells for up to 50 rooms. Growth ($149/mo) covers up to 150 rooms with priority support.',
    faq_q7: 'Is there a free trial?', faq_a7: 'Yes — you can start a free trial and explore the full platform before committing. No credit card pressure, cancel anytime.',
    faq_q8: 'Do you offer online check-in?', faq_a8: 'Yes. Guests can complete check-in online before arrival — providing their details and ID/passport documents through a secure form. You can review and export this information from your dashboard.',
    faq_q9: 'Is there a mobile app?', faq_a9: 'Yes, Hostlio Pro includes a mobile app so you can manage reservations, guests, pricing, and messages on the go — even offline.',
    faq_q10: 'Can I cancel anytime?', faq_a10: 'Absolutely. There are no long-term contracts. You can manage or cancel your subscription anytime from the billing portal.',
    plan_desc_starter: 'Perfect for small independent hotels getting started with automation.',
    plan_desc_pro: 'The complete solution for busy hotels on all channels.',
    plan_desc_growth: 'Scale across multiple properties with concierge support.',
    foot_privacy: 'Privacy Policy', foot_terms: 'Terms of Service',
  },
  tr: {
    nav_features: 'Özellikler', nav_pricing: 'Fiyatlandırma', nav_demo: 'Demo', nav_dashboard: 'Panele Git', nav_getstarted: 'Başla',
    hero_badge: 'Yapay Zeka Destekli Otel Yönetimi',
    hero_title_1: 'Yapay Zeka Destekli<br>Resepsiyonunuz.',
    hero_title_2: '7/24, 30+ Dilde.',
    hero_sub: 'Yanıtsız mesajlar yüzünden rezervasyon kaybetmeyi bırakın. Booking.com, Airbnb, E-posta, Web Sohbet ve Telegram üzerinden misafir iletişimini otomatikleştirin — aylık $49\'dan başlayan fiyatlarla.',
    hero_cta_trial: 'Ücretsiz Deneyin →', hero_cta_demo: 'Demo İzle',
    pain_label: 'Sorunlar', pain_title: 'Tanıdık geldi mi?', pain_sub: 'Her bağımsız otel sahibi bu sorunları bilir. Hostlio Pro\'yu hepsini çözmek için geliştirdik.',
    pain_1: '"Misafirler gece 3\'te mesaj atıyor. Kaçırıyorsunuz. Başka yerden rezervasyon yapıyorlar."', pain_2: '"5 platform. 5 giriş. Her gün saatlerce kayıp."', pain_3: '"Bir yanlış tıklama. Çifte rezervasyon. Kızgın misafirler."', pain_4: '"Düşük sezon vuruyor. Boş odaları doldurmak için araç yok."',
    feat_label: 'Özellikler', feat_title: 'Otelinizin ihtiyacı olan her şey.<br>Gereksiz hiçbir şey yok.', feat_sub: 'Beş farklı aracın yerini alan tek, sade ve şık bir platform.',
    feat_1_t: 'AI Misafir Mesajlaşma', feat_1_d: 'OTA\'lar, E-posta, Web Sohbet ve Telegram üzerinden 30+ dilde yanıt. 7/24 — parmağınızı bile kıpırdatmadan.',
    feat_2_t: 'Oda Takvimi', feat_2_d: 'Rezervasyonları sürükle-bırak. Her odayı tek bakışta görün.',
    feat_3_t: '100+ OTA Entegrasyonu', feat_3_d: 'Channex üzerinden Booking.com, Airbnb, Expedia, Agoda, Trip.com ve 100+ kanal. Gerçek zamanlı senkron. Sıfır çifte rezervasyon.',
    feat_4_t: 'PDF Vize Formları', feat_4_d: 'Otel logonuzla otomatik oluşturun. Check-in\'de anında paylaşın.',
    feat_5_t: 'Transfer & Turlar', feat_5_d: 'Misafirlere otomatik havalimanı transferi satın. Ekstra gelir, sıfır çaba.',
    feat_6_t: 'Mobil Uygulama', feat_6_d: 'Otelinizi çevrimdışı yönetin. İnternetsiz çalışır. Her zaman cebinizde.',
    how_label: 'Nasıl Çalışır', how_title: '30 dakikada hazır', how_sub: 'IT ekibi gerekmez. Karmaşık kurulum yok. Sadece dört basit adım.',
    how_1_t: 'Kanallarınızı bağlayın', how_1_d: 'Booking.com, Airbnb, Expedia ve 100+ kanalı tek tıkla bağlayın. Rezervasyonlarınız otomatik aktarılır.',
    how_2_t: 'AI mesajları yönetir', how_2_d: 'AI asistanınız her misafire — kendi dilinde — gece gündüz yanıt verir. Siz onaylarsınız, asla tekrarlamazsınız.',
    how_3_t: 'Tek panelden yönetin', how_3_d: 'Tüm odaları, kanalları, mesajları tek güzel yerde görün. Her gün 3+ saat kazanın.',
    how_4_t: 'Gelirinizi büyütün', how_4_d: 'Havalimanı transferleri, turlar ve ek satışları otomatik sunun. AI her misafire ekstralar önerir.',
    price_label: 'Fiyatlandırma', price_title: 'Basit, şeffaf fiyatlandırma', price_sub: 'Gizli ücret yok. Uzun vadeli sözleşme yok. İstediğiniz zaman iptal.',
    comp_label: 'Karşılaştırma', comp_title: 'Oteller neden Hostlio Pro\'yu seçiyor', comp_sub: 'Eski otel yazılımlarıyla nasıl kıyaslandığımızı görün.',
    cta_title: 'Otelinizi otomatikleştirmeye hazır mısınız?',
    banner_earlybird: '🔥 Erken Kayıt Fırsatı — İlk 50 müşteriye özel: tüm planlarda %20 indirim!',
    trust_worldwide: 'Dünya çapında bağımsız oteller tarafından tercih ediliyor', trust_label: '20+ ülkede bağımsız oteller tarafından kullanılıyor — senkronize olduğu kanallar',
    plan_cta: 'Ücretsiz Deneyin', plan_cta_arrow: 'Ücretsiz Deneyin →',
    cta_sub: 'Hostlio Pro ile her gün 3+ saat tasarruf eden bağımsız otellere katılın.', cta_btn: 'Ücretsiz Deneyin →',
    foot_product: 'Ürün', foot_company: 'Şirket', foot_legal: 'Yasal', foot_how: 'Nasıl Çalışır', foot_compare: 'Karşılaştır', foot_about: 'Hakkımızda', foot_contact: 'İletişim',
    stat_countries: '20+ Ülke', stat_sync: '100+ Kanal Senkron', stat_overbook: 'Sıfır çifte rezervasyon garantisi',
    f_1prop: '1 tesis', f_10rooms: '10 odaya kadar', f_5kmsg: 'Aylık 5.000 AI mesajı', f_otaemail: 'OTA + E-posta mesajlaşma', f_roomrack: 'Oda Takvimi', f_pdfvisa: 'PDF Vize Formları',
    f_50rooms: '50 odaya kadar', f_20kmsg: 'Aylık 20.000 AI mesajı', f_allchan: 'Tüm kanallar (100+ OTA)', f_allmsg: 'OTA + E-posta + Web Sohbet + Telegram', f_transfer: 'Transfer & Tur satışı', f_mobile: 'Mobil Uygulama',
    f_multiprop: 'Çoklu tesis', f_150rooms: '150 odaya kadar', f_50kmsg: 'Aylık 50.000 AI mesajı', f_prioritysync: 'Tüm 100+ kanal + öncelikli senkron', f_prioritysup: 'Öncelikli destek (2 saat yanıt)', f_onboarding: 'Özel kurulum görüşmesi', f_whitelabel: 'Beyaz etiket seçenekleri',
    plan_note: '14 gün ücretsiz deneme',
    ent_name: 'KURUMSAL', ent_price: 'Özel Fiyatlandırma', ent_desc: 'Büyük tesisler ve otel grupları için.',
    ent_1: '✓ 150+ oda', ent_2: '✓ Sınırsız AI mesajı', ent_3: '✓ Growth\'taki her şey', ent_4: '✓ Özel hesap yöneticisi', ent_5: '✓ Özel entegrasyonlar', ent_6: '✓ SLA garantisi', ent_cta: 'Bize Ulaşın →',
    comp_feature: 'Özellik', comp_r1: 'AI misafir mesajlaşma otomasyonu', comp_r2: '30+ dilde AI yanıtları', comp_r4: 'Görsel oda takvimi', comp_r6: 'Çevrimdışı mobil uygulama', comp_price: 'Başlangıç fiyatı',
    cta_trial: '14 gün ücretsiz deneme', cta_cancel: 'İstediğiniz zaman iptal',
    foot_desc: 'Dünya çapında bağımsız oteller için yapay zeka destekli otel yönetimi.',
    earlybird: '🔥 Erken Kayıt', comp_expensive: 'ölçeklendikçe pahalı',
    comp_r3: '100+ OTA entegrasyonu', comp_r5: 'Transfer & tur satışı', comp_r7: 'PDF vize formları (otomatik)', comp_perlisting: 'İlan başına',
    faq_back: '← Ana sayfaya dön', faq_title: 'Sıkça Sorulan Sorular', faq_sub: 'Hostlio Pro hakkında bilmeniz gereken her şey. Yanıt bulamadınız mı?', faq_contact: 'Bize ulaşın', faq_cta: 'Ücretsiz Deneyin →',
    faq_q1: 'Hostlio Pro nedir?', faq_a1: 'Hostlio Pro; bağımsız oteller, butik pansiyonlar ve hosteller için yapay zeka destekli bir otel yönetim platformudur. Misafir mesajlaşmasını 30+ dilde otomatikleştirir, müsaitliğinizi Channex üzerinden 100+ OTA kanalında senkronize eder ve tesisinizi yönetmeniz için tek bir panel sunar.',
    faq_q2: 'Kurulum ne kadar sürer?', faq_a2: 'Çoğu otel yaklaşık 30 dakikada hazır olur. Kanallarınızı bağlar, odalarınızı ve rezervasyonlarınızı içe aktarır ve AI asistanınızı yapılandırırsınız — IT ekibi gerekmez.',
    faq_q3: 'Hangi rezervasyon kanallarını destekliyorsunuz?', faq_a3: 'Channex entegrasyonumuz sayesinde Hostlio Pro; Booking.com, Airbnb, Expedia, Agoda ve Trip.com dahil 100+ OTA\'ya bağlanır. Müsaitlik ve fiyatlar gerçek zamanlı senkronize olarak çifte rezervasyonu önler. <a href="/channels.html" style="color:var(--orange);font-weight:600">Tam kanal listemize</a> bakın.',
    faq_q4: 'AI hangi dilleri destekliyor?', faq_a4: 'AI asistanı misafirlere 30+ dilde otomatik yanıt verir — misafirin dilini algılar ve 7/24 doğal şekilde yanıtlar, sizden ekstra çaba gerektirmez.',
    faq_q5: 'Hangi mesajlaşma kanalları destekleniyor?', faq_a5: 'Hostlio Pro; OTA gelen kutuları (Booking.com, Airbnb), E-posta, web sitenizdeki sohbet widget\'ı ve Telegram üzerinden misafir mesajlarını yönetir. Düzenli olarak yeni kanallar eklenir.',
    faq_q6: 'Maliyeti ne kadar?', faq_a6: 'Planlar 10 odaya kadar aylık $49\'dan başlar (Starter, normalde $59). Pro ($89/ay) 50 odaya kadar tüm kanalları ve transfer & tur ek satışlarını ekler. Growth ($149/ay) öncelikli destekle 150 odaya kadar kapsar.',
    faq_q7: 'Ücretsiz deneme var mı?', faq_a7: 'Evet — taahhütte bulunmadan önce ücretsiz deneme başlatıp platformun tamamını keşfedebilirsiniz. Kredi kartı baskısı yok, istediğiniz zaman iptal edin.',
    faq_q8: 'Online check-in sunuyor musunuz?', faq_a8: 'Evet. Misafirler varıştan önce online check-in yapabilir — bilgilerini ve kimlik/pasaport belgelerini güvenli bir form aracılığıyla iletir. Bu bilgileri panelinizden inceleyip dışa aktarabilirsiniz.',
    faq_q9: 'Mobil uygulama var mı?', faq_a9: 'Evet, Hostlio Pro rezervasyonları, misafirleri, fiyatlandırmayı ve mesajları hareket halindeyken — hatta çevrimdışı — yönetebilmeniz için bir mobil uygulama içerir.',
    faq_q10: 'İstediğim zaman iptal edebilir miyim?', faq_a10: 'Kesinlikle. Uzun vadeli sözleşme yoktur. Aboneliğinizi istediğiniz zaman faturalandırma portalından yönetebilir veya iptal edebilirsiniz.',
    plan_desc_starter: 'Otomasyona yeni başlayan küçük bağımsız oteller için ideal.',
    plan_desc_pro: 'Tüm kanallarda yoğun oteller için eksiksiz çözüm.',
    plan_desc_growth: 'Concierge desteğiyle birden fazla tesise ölçeklenin.',
    foot_privacy: 'Gizlilik Politikası', foot_terms: 'Kullanım Şartları',
  },
  es: {
    nav_features: 'Funciones', nav_pricing: 'Precios', nav_demo: 'Demo', nav_dashboard: 'Ir al Panel', nav_getstarted: 'Empezar',
    hero_badge: 'Gestión Hotelera con IA',
    hero_title_1: 'Su Recepción<br>con IA.',
    hero_title_2: '24/7, en más de 30 idiomas.',
    hero_sub: 'Deje de perder reservas por mensajes sin responder. Automatice la comunicación con huéspedes en Booking.com, Airbnb, Email, Chat Web y Telegram — desde $49/mes.',
    hero_cta_trial: 'Prueba Gratis →', hero_cta_demo: 'Ver Demo',
    pain_label: 'Problemas', pain_title: '¿Te suena familiar?', pain_sub: 'Todo hotelero independiente conoce estos problemas. Creamos Hostlio Pro para resolverlos todos.',
    pain_1: '"Los huéspedes escriben a las 3am. No lo ves. Reservan en otro sitio."', pain_2: '"5 plataformas. 5 accesos. Horas perdidas cada día."', pain_3: '"Un clic erróneo. Reserva doble. Huéspedes enfadados."', pain_4: '"La temporada baja golpea fuerte. Sin herramientas para llenar habitaciones."',
    feat_label: 'Funciones', feat_title: 'Todo lo que tu hotel necesita.<br>Nada que no.', feat_sub: 'Una plataforma simple y elegante que reemplaza cinco herramientas distintas.',
    feat_1_t: 'Mensajería con IA', feat_1_d: 'Responde en más de 30 idiomas en OTAs, Email, Chat Web y Telegram. 24/7 — sin mover un dedo.',
    feat_2_t: 'Calendario de Habitaciones', feat_2_d: 'Arrastra y suelta reservas. Ve cada habitación de un vistazo.',
    feat_3_t: 'Integración 100+ OTA', feat_3_d: 'Booking.com, Airbnb, Expedia, Agoda, Trip.com y más de 100 vía Channex. Sincronización en tiempo real. Cero overbooking.',
    feat_4_t: 'Formularios de Visa PDF', feat_4_d: 'Genera automáticamente con el logo de tu hotel. Comparte al instante en el check-in.',
    feat_5_t: 'Traslados y Tours', feat_5_d: 'Vende traslados al aeropuerto automáticamente. Ingresos extra, cero esfuerzo.',
    feat_6_t: 'App Móvil', feat_6_d: 'Gestiona tu hotel sin conexión. Funciona sin internet. Siempre en tu bolsillo.',
    how_label: 'Cómo Funciona', how_title: 'Listo en 30 minutos', how_sub: 'Sin equipo de TI. Sin configuración compleja. Solo cuatro pasos simples.',
    how_1_t: 'Conecta tus canales', how_1_d: 'Vincula Booking.com, Airbnb, Expedia y más de 100 con un clic. Tus reservas se importan automáticamente.',
    how_2_t: 'La IA gestiona mensajes', how_2_d: 'Tu asistente de IA responde a cada huésped — en su idioma — día y noche. Tú revisas, nunca repites.',
    how_3_t: 'Gestiona desde un panel', how_3_d: 'Ve todas las habitaciones, canales y mensajes en un solo lugar. Recupera más de 3 horas al día.',
    how_4_t: 'Aumenta tus ingresos', how_4_d: 'Ofrece traslados, tours y extras automáticamente. Tu IA sugiere extras a cada huésped.',
    price_label: 'Precios', price_title: 'Precios simples y transparentes', price_sub: 'Sin tarifas ocultas. Sin contratos largos. Cancela cuando quieras.',
    comp_label: 'Comparación', comp_title: 'Por qué los hoteles eligen Hostlio Pro', comp_sub: 'Mira cómo nos comparamos con el software hotelero tradicional.',
    cta_title: '¿Listo para automatizar tu hotel?',
    banner_earlybird: '🔥 Oferta Early Bird — Limitada a los próximos 50 clientes: ¡20% de descuento en todos los planes!',
    trust_worldwide: 'Con la confianza de hoteles independientes en todo el mundo', trust_label: 'Con la confianza de hoteles independientes en más de 20 países — se sincroniza con',
    plan_cta: 'Prueba Gratis', plan_cta_arrow: 'Prueba Gratis →',
    cta_sub: 'Únete a los hoteles independientes que ahorran más de 3 horas al día con Hostlio Pro.', cta_btn: 'Prueba Gratis →',
    foot_product: 'Producto', foot_company: 'Empresa', foot_legal: 'Legal', foot_how: 'Cómo Funciona', foot_compare: 'Comparar', foot_about: 'Nosotros', foot_contact: 'Contacto',
    stat_countries: '20+ Países', stat_sync: 'Sincronización 100+ Canales', stat_overbook: 'Cero overbooking garantizado',
    f_1prop: '1 propiedad', f_10rooms: 'Hasta 10 habitaciones', f_5kmsg: '5.000 mensajes IA/mes', f_otaemail: 'Mensajería OTA + Email', f_roomrack: 'Calendario de Habitaciones', f_pdfvisa: 'Formularios de Visa PDF',
    f_50rooms: 'Hasta 50 habitaciones', f_20kmsg: '20.000 mensajes IA/mes', f_allchan: 'Todos los canales (100+ OTAs)', f_allmsg: 'OTA + Email + Chat Web + Telegram', f_transfer: 'Ventas de traslados y tours', f_mobile: 'App Móvil',
    f_multiprop: 'Multipropiedad', f_150rooms: 'Hasta 150 habitaciones', f_50kmsg: '50.000 mensajes IA/mes', f_prioritysync: 'Todos los 100+ canales + sync prioritaria', f_prioritysup: 'Soporte prioritario (respuesta 2h)', f_onboarding: 'Llamada de incorporación personalizada', f_whitelabel: 'Opciones de marca blanca',
    plan_note: 'Prueba gratis de 14 días',
    ent_name: 'EMPRESA', ent_price: 'Precio Personalizado', ent_desc: 'Para grandes propiedades y grupos hoteleros.',
    ent_1: '✓ Más de 150 habitaciones', ent_2: '✓ Mensajes IA ilimitados', ent_3: '✓ Todo lo de Growth', ent_4: '✓ Gestor de cuenta dedicado', ent_5: '✓ Integraciones personalizadas', ent_6: '✓ Garantía SLA', ent_cta: 'Contáctanos →',
    comp_feature: 'Función', comp_r1: 'Automatización de mensajes con IA', comp_r2: 'Respuestas IA en más de 30 idiomas', comp_r4: 'Calendario visual de habitaciones', comp_r6: 'App móvil sin conexión', comp_price: 'Precio inicial',
    cta_trial: 'Prueba gratis de 14 días', cta_cancel: 'Cancela cuando quieras',
    foot_desc: 'Gestión hotelera con IA para hoteles independientes de todo el mundo.',
    earlybird: '🔥 Early Bird', comp_expensive: 'caro a gran escala',
    comp_r3: 'Integración 100+ OTA', comp_r5: 'Ventas de traslados y tours', comp_r7: 'Formularios de visa PDF (auto)', comp_perlisting: 'Por anuncio',
    faq_back: '← Volver al inicio', faq_title: 'Preguntas Frecuentes', faq_sub: '¿Todo lo que necesitas saber sobre Hostlio Pro. ¿No encuentras una respuesta?', faq_contact: 'Contáctanos', faq_cta: 'Prueba Gratis →',
    faq_q1: '¿Qué es Hostlio Pro?', faq_a1: 'Hostlio Pro es una plataforma de gestión hotelera con IA para hoteles independientes, B&Bs boutique y hostales. Automatiza la mensajería con huéspedes en más de 30 idiomas, sincroniza tu disponibilidad en más de 100 canales OTA vía Channex y te ofrece un único panel para gestionar tu propiedad.',
    faq_q2: '¿Cuánto tarda la configuración?', faq_a2: 'La mayoría de los hoteles están operativos en unos 30 minutos. Conectas tus canales, importas tus habitaciones y reservas, y configuras tu asistente de IA — sin equipo de TI.',
    faq_q3: '¿Qué canales de reserva admiten?', faq_a3: 'A través de nuestra integración con Channex, Hostlio Pro se conecta a más de 100 OTAs incluyendo Booking.com, Airbnb, Expedia, Agoda y Trip.com. La disponibilidad y las tarifas se sincronizan en tiempo real para evitar overbookings. Consulta nuestra <a href="/channels.html" style="color:var(--orange);font-weight:600">lista completa de canales</a>.',
    faq_q4: '¿Qué idiomas admite la IA?', faq_a4: 'El asistente de IA responde a los huéspedes en más de 30 idiomas automáticamente — detecta el idioma del huésped y responde con naturalidad, 24/7, sin esfuerzo extra para ti.',
    faq_q5: '¿Qué canales de mensajería se admiten?', faq_a5: 'Hostlio Pro gestiona los mensajes de huéspedes en bandejas OTA (Booking.com, Airbnb), Email, el chat de tu web y Telegram. Se añaden más canales regularmente.',
    faq_q6: '¿Cuánto cuesta?', faq_a6: 'Los planes empiezan en $49/mes (Starter, normalmente $59) para hasta 10 habitaciones. Pro ($89/mo) añade todos los canales más ventas de traslados y tours para hasta 50 habitaciones. Growth ($149/mo) cubre hasta 150 habitaciones con soporte prioritario.',
    faq_q7: '¿Hay prueba gratuita?', faq_a7: 'Sí — puedes empezar una prueba gratis y explorar toda la plataforma antes de comprometerte. Sin presión de tarjeta de crédito, cancela cuando quieras.',
    faq_q8: '¿Ofrecen check-in online?', faq_a8: 'Sí. Los huéspedes pueden completar el check-in online antes de llegar — proporcionando sus datos y documentos de identidad/pasaporte mediante un formulario seguro. Puedes revisar y exportar esta información desde tu panel.',
    faq_q9: '¿Hay app móvil?', faq_a9: 'Sí, Hostlio Pro incluye una app móvil para que gestiones reservas, huéspedes, precios y mensajes sobre la marcha — incluso sin conexión.',
    faq_q10: '¿Puedo cancelar cuando quiera?', faq_a10: 'Por supuesto. No hay contratos a largo plazo. Puedes gestionar o cancelar tu suscripción en cualquier momento desde el portal de facturación.',
    plan_desc_starter: 'Perfecto para pequeños hoteles independientes que empiezan con la automatización.',
    plan_desc_pro: 'La solución completa para hoteles activos en todos los canales.',
    plan_desc_growth: 'Escala en múltiples propiedades con soporte de conserjería.',
    foot_privacy: 'Política de Privacidad', foot_terms: 'Términos de Servicio',
  },
  it: {
    nav_features: 'Funzioni', nav_pricing: 'Prezzi', nav_demo: 'Demo', nav_dashboard: 'Vai alla Dashboard', nav_getstarted: 'Inizia',
    hero_badge: 'Gestione Alberghiera con IA',
    hero_title_1: 'La tua Reception<br>con IA.',
    hero_title_2: '24/7, in oltre 30 lingue.',
    hero_sub: 'Smetti di perdere prenotazioni per messaggi senza risposta. Automatizza la comunicazione con gli ospiti su Booking.com, Airbnb, Email, Chat Web e Telegram — a partire da $49/mese.',
    hero_cta_trial: 'Prova Gratis →', hero_cta_demo: 'Guarda la Demo',
    pain_label: 'Problemi', pain_title: 'Ti suona familiare?', pain_sub: 'Ogni albergatore indipendente conosce questi problemi. Abbiamo creato Hostlio Pro per risolverli tutti.',
    pain_1: '"Gli ospiti scrivono alle 3 di notte. Te lo perdi. Prenotano altrove."', pain_2: '"5 piattaforme. 5 accessi. Ore perse ogni giorno."', pain_3: '"Un clic sbagliato. Doppia prenotazione. Ospiti arrabbiati."', pain_4: '"La bassa stagione colpisce duro. Nessuno strumento per riempire le camere."',
    feat_label: 'Funzioni', feat_title: 'Tutto ciò che serve al tuo hotel.<br>Niente di superfluo.', feat_sub: 'Una piattaforma semplice ed elegante che sostituisce cinque strumenti diversi.',
    feat_1_t: 'Messaggistica con IA', feat_1_d: 'Risponde in oltre 30 lingue su OTA, Email, Chat Web e Telegram. 24/7 — senza muovere un dito.',
    feat_2_t: 'Calendario Camere', feat_2_d: 'Trascina e rilascia le prenotazioni. Vedi ogni camera a colpo d\'occhio.',
    feat_3_t: 'Integrazione 100+ OTA', feat_3_d: 'Booking.com, Airbnb, Expedia, Agoda, Trip.com e oltre 100 tramite Channex. Sincronizzazione in tempo reale. Zero overbooking.',
    feat_4_t: 'Moduli Visto PDF', feat_4_d: 'Genera automaticamente con il logo del tuo hotel. Condividi subito al check-in.',
    feat_5_t: 'Transfer e Tour', feat_5_d: 'Vendi transfer aeroportuali automaticamente. Entrate extra, zero sforzo.',
    feat_6_t: 'App Mobile', feat_6_d: 'Gestisci il tuo hotel offline. Funziona senza internet. Sempre in tasca.',
    how_label: 'Come Funziona', how_title: 'Operativo in 30 minuti', how_sub: 'Nessun team IT. Nessuna configurazione complessa. Solo quattro semplici passi.',
    how_1_t: 'Collega i tuoi canali', how_1_d: 'Collega Booking.com, Airbnb, Expedia e oltre 100 con un clic. Le prenotazioni si importano automaticamente.',
    how_2_t: 'L\'IA gestisce i messaggi', how_2_d: 'Il tuo assistente IA risponde a ogni ospite — nella sua lingua — giorno e notte. Tu controlli, mai ripeti.',
    how_3_t: 'Gestisci da una dashboard', how_3_d: 'Vedi tutte le camere, i canali e i messaggi in un unico posto. Recupera oltre 3 ore al giorno.',
    how_4_t: 'Aumenta i ricavi', how_4_d: 'Offri transfer, tour ed extra automaticamente. La tua IA suggerisce extra a ogni ospite.',
    price_label: 'Prezzi', price_title: 'Prezzi semplici e trasparenti', price_sub: 'Nessun costo nascosto. Nessun contratto a lungo termine. Disdici quando vuoi.',
    comp_label: 'Confronto', comp_title: 'Perché gli hotel scelgono Hostlio Pro', comp_sub: 'Scopri come ci confrontiamo con i software alberghieri tradizionali.',
    cta_title: 'Pronto ad automatizzare il tuo hotel?',
    banner_earlybird: '🔥 Offerta Early Bird — Limitata ai prossimi 50 clienti: 20% di sconto su tutti i piani!',
    trust_worldwide: 'Scelto da hotel indipendenti in tutto il mondo', trust_label: 'Scelto da hotel indipendenti in oltre 20 paesi — si sincronizza con',
    plan_cta: 'Prova Gratis', plan_cta_arrow: 'Prova Gratis →',
    cta_sub: 'Unisciti agli hotel indipendenti che risparmiano oltre 3 ore al giorno con Hostlio Pro.', cta_btn: 'Prova Gratis →',
    foot_product: 'Prodotto', foot_company: 'Azienda', foot_legal: 'Legale', foot_how: 'Come Funziona', foot_compare: 'Confronta', foot_about: 'Chi Siamo', foot_contact: 'Contatti',
    stat_countries: '20+ Paesi', stat_sync: 'Sincronizzazione 100+ Canali', stat_overbook: 'Zero overbooking garantito',
    f_1prop: '1 struttura', f_10rooms: 'Fino a 10 camere', f_5kmsg: '5.000 messaggi IA/mese', f_otaemail: 'Messaggistica OTA + Email', f_roomrack: 'Calendario Camere', f_pdfvisa: 'Moduli Visto PDF',
    f_50rooms: 'Fino a 50 camere', f_20kmsg: '20.000 messaggi IA/mese', f_allchan: 'Tutti i canali (100+ OTA)', f_allmsg: 'OTA + Email + Chat Web + Telegram', f_transfer: 'Vendita transfer e tour', f_mobile: 'App Mobile',
    f_multiprop: 'Multi-struttura', f_150rooms: 'Fino a 150 camere', f_50kmsg: '50.000 messaggi IA/mese', f_prioritysync: 'Tutti i 100+ canali + sync prioritaria', f_prioritysup: 'Supporto prioritario (risposta 2h)', f_onboarding: 'Chiamata di onboarding personalizzata', f_whitelabel: 'Opzioni white-label',
    plan_note: 'Prova gratuita di 14 giorni',
    ent_name: 'ENTERPRISE', ent_price: 'Prezzo Personalizzato', ent_desc: 'Per grandi strutture e gruppi alberghieri.',
    ent_1: '✓ Oltre 150 camere', ent_2: '✓ Messaggi IA illimitati', ent_3: '✓ Tutto di Growth', ent_4: '✓ Account manager dedicato', ent_5: '✓ Integrazioni personalizzate', ent_6: '✓ Garanzia SLA', ent_cta: 'Contattaci →',
    comp_feature: 'Funzione', comp_r1: 'Automazione messaggistica con IA', comp_r2: 'Risposte IA in oltre 30 lingue', comp_r4: 'Calendario camere visivo', comp_r6: 'App mobile offline', comp_price: 'Prezzo iniziale',
    cta_trial: 'Prova gratuita di 14 giorni', cta_cancel: 'Disdici quando vuoi',
    foot_desc: 'Gestione alberghiera con IA per hotel indipendenti in tutto il mondo.',
    earlybird: '🔥 Early Bird', comp_expensive: 'costoso su larga scala',
    comp_r3: 'Integrazione 100+ OTA', comp_r5: 'Vendita transfer e tour', comp_r7: 'Moduli visto PDF (auto)', comp_perlisting: 'Per annuncio',
    faq_back: '← Torna alla home', faq_title: 'Domande Frequenti', faq_sub: 'Tutto ciò che devi sapere su Hostlio Pro. Non trovi una risposta?', faq_contact: 'Contattaci', faq_cta: 'Prova Gratis →',
    faq_q1: "Cos'è Hostlio Pro?", faq_a1: 'Hostlio Pro è una piattaforma di gestione alberghiera con IA per hotel indipendenti, B&B boutique e ostelli. Automatizza la messaggistica con gli ospiti in oltre 30 lingue, sincronizza la disponibilità su oltre 100 canali OTA tramite Channex e ti offre un\'unica dashboard per gestire la tua struttura.',
    faq_q2: 'Quanto tempo richiede la configurazione?', faq_a2: 'La maggior parte degli hotel è operativa in circa 30 minuti. Colleghi i canali, importi camere e prenotazioni e configuri il tuo assistente IA — senza team IT.',
    faq_q3: 'Quali canali di prenotazione supportate?', faq_a3: 'Tramite la nostra integrazione Channex, Hostlio Pro si connette a oltre 100 OTA tra cui Booking.com, Airbnb, Expedia, Agoda e Trip.com. Disponibilità e tariffe si sincronizzano in tempo reale per evitare overbooking. Consulta la nostra <a href="/channels.html" style="color:var(--orange);font-weight:600">lista completa dei canali</a>.',
    faq_q4: 'Quali lingue supporta l\'IA?', faq_a4: 'L\'assistente IA risponde agli ospiti in oltre 30 lingue automaticamente — rileva la lingua dell\'ospite e risponde in modo naturale, 24/7, senza sforzo extra da parte tua.',
    faq_q5: 'Quali canali di messaggistica sono supportati?', faq_a5: 'Hostlio Pro gestisce i messaggi degli ospiti tramite inbox OTA (Booking.com, Airbnb), Email, il widget chat del tuo sito e Telegram. Vengono aggiunti regolarmente nuovi canali.',
    faq_q6: 'Quanto costa?', faq_a6: 'I piani partono da $49/mese (Starter, normalmente $59) per un massimo di 10 camere. Pro ($89/mo) aggiunge tutti i canali più vendite di transfer e tour per un massimo di 50 camere. Growth ($149/mo) copre fino a 150 camere con supporto prioritario.',
    faq_q7: "C'è una prova gratuita?", faq_a7: 'Sì — puoi iniziare una prova gratuita ed esplorare l\'intera piattaforma prima di impegnarti. Nessuna pressione sulla carta di credito, disdici quando vuoi.',
    faq_q8: 'Offrite il check-in online?', faq_a8: 'Sì. Gli ospiti possono completare il check-in online prima dell\'arrivo — fornendo i propri dati e documenti d\'identità/passaporto tramite un modulo sicuro. Puoi rivedere ed esportare queste informazioni dalla dashboard.',
    faq_q9: "C'è un'app mobile?", faq_a9: 'Sì, Hostlio Pro include un\'app mobile per gestire prenotazioni, ospiti, prezzi e messaggi in movimento — anche offline.',
    faq_q10: 'Posso disdire quando voglio?', faq_a10: 'Assolutamente. Non ci sono contratti a lungo termine. Puoi gestire o disdire l\'abbonamento in qualsiasi momento dal portale di fatturazione.',
    plan_desc_starter: 'Perfetto per piccoli hotel indipendenti che iniziano con l\'automazione.',
    plan_desc_pro: 'La soluzione completa per hotel impegnati su tutti i canali.',
    plan_desc_growth: 'Scala su più strutture con supporto concierge.',
    foot_privacy: 'Informativa sulla Privacy', foot_terms: 'Termini di Servizio',
  },
  pt: {
    nav_features: 'Recursos', nav_pricing: 'Preços', nav_demo: 'Demo', nav_dashboard: 'Ir para o Painel', nav_getstarted: 'Começar',
    hero_badge: 'Gestão Hoteleira com IA',
    hero_title_1: 'A sua Receção<br>com IA.',
    hero_title_2: '24/7, em mais de 30 idiomas.',
    hero_sub: 'Pare de perder reservas por mensagens sem resposta. Automatize a comunicação com hóspedes no Booking.com, Airbnb, Email, Chat Web e Telegram — a partir de $49/mês.',
    hero_cta_trial: 'Teste Grátis →', hero_cta_demo: 'Ver Demo',
    pain_label: 'Problemas', pain_title: 'Soa familiar?', pain_sub: 'Todo hoteleiro independente conhece estes problemas. Criámos o Hostlio Pro para resolvê-los todos.',
    pain_1: '"Os hóspedes escrevem às 3 da manhã. Você perde. Reservam noutro lado."', pain_2: '"5 plataformas. 5 logins. Horas perdidas todos os dias."', pain_3: '"Um clique errado. Reserva dupla. Hóspedes irritados."', pain_4: '"A época baixa atinge forte. Sem ferramentas para encher quartos."',
    feat_label: 'Recursos', feat_title: 'Tudo o que o seu hotel precisa.<br>Nada que não.', feat_sub: 'Uma plataforma simples e elegante que substitui cinco ferramentas diferentes.',
    feat_1_t: 'Mensagens com IA', feat_1_d: 'Responde em mais de 30 idiomas em OTAs, Email, Chat Web e Telegram. 24/7 — sem mexer um dedo.',
    feat_2_t: 'Calendário de Quartos', feat_2_d: 'Arraste e solte reservas. Veja cada quarto num relance.',
    feat_3_t: 'Integração 100+ OTA', feat_3_d: 'Booking.com, Airbnb, Expedia, Agoda, Trip.com e mais de 100 via Channex. Sincronização em tempo real. Zero overbooking.',
    feat_4_t: 'Formulários de Visto PDF', feat_4_d: 'Gere automaticamente com o logótipo do seu hotel. Partilhe instantaneamente no check-in.',
    feat_5_t: 'Transferes e Tours', feat_5_d: 'Venda transferes do aeroporto automaticamente. Receita extra, zero esforço.',
    feat_6_t: 'App Móvel', feat_6_d: 'Faça a gestão do seu hotel offline. Funciona sem internet. Sempre no seu bolso.',
    how_label: 'Como Funciona', how_title: 'Pronto em 30 minutos', how_sub: 'Sem equipa de TI. Sem configuração complexa. Apenas quatro passos simples.',
    how_1_t: 'Ligue os seus canais', how_1_d: 'Ligue Booking.com, Airbnb, Expedia e mais de 100 com um clique. As suas reservas são importadas automaticamente.',
    how_2_t: 'A IA gere as mensagens', how_2_d: 'O seu assistente de IA responde a cada hóspede — no idioma dele — dia e noite. Você revê, nunca repete.',
    how_3_t: 'Faça a gestão num painel', how_3_d: 'Veja todos os quartos, canais e mensagens num só lugar. Recupere mais de 3 horas por dia.',
    how_4_t: 'Aumente a sua receita', how_4_d: 'Ofereça transferes, tours e extras automaticamente. A sua IA sugere extras a cada hóspede.',
    price_label: 'Preços', price_title: 'Preços simples e transparentes', price_sub: 'Sem taxas ocultas. Sem contratos longos. Cancele quando quiser.',
    comp_label: 'Comparação', comp_title: 'Porque os hotéis escolhem o Hostlio Pro', comp_sub: 'Veja como nos comparamos com o software hoteleiro tradicional.',
    cta_title: 'Pronto para automatizar o seu hotel?',
    banner_earlybird: '🔥 Oferta Early Bird — Limitada aos próximos 50 clientes: 20% de desconto em todos os planos!',
    trust_worldwide: 'Com a confiança de hotéis independentes em todo o mundo', trust_label: 'Com a confiança de hotéis independentes em mais de 20 países — sincroniza com',
    plan_cta: 'Teste Grátis', plan_cta_arrow: 'Teste Grátis →',
    cta_sub: 'Junte-se aos hotéis independentes que poupam mais de 3 horas por dia com o Hostlio Pro.', cta_btn: 'Teste Grátis →',
    foot_product: 'Produto', foot_company: 'Empresa', foot_legal: 'Legal', foot_how: 'Como Funciona', foot_compare: 'Comparar', foot_about: 'Sobre', foot_contact: 'Contacto',
    stat_countries: '20+ Países', stat_sync: 'Sincronização 100+ Canais', stat_overbook: 'Zero overbooking garantido',
    f_1prop: '1 propriedade', f_10rooms: 'Até 10 quartos', f_5kmsg: '5.000 mensagens IA/mês', f_otaemail: 'Mensagens OTA + Email', f_roomrack: 'Calendário de Quartos', f_pdfvisa: 'Formulários de Visto PDF',
    f_50rooms: 'Até 50 quartos', f_20kmsg: '20.000 mensagens IA/mês', f_allchan: 'Todos os canais (100+ OTAs)', f_allmsg: 'OTA + Email + Chat Web + Telegram', f_transfer: 'Vendas de transferes e tours', f_mobile: 'App Móvel',
    f_multiprop: 'Multipropriedade', f_150rooms: 'Até 150 quartos', f_50kmsg: '50.000 mensagens IA/mês', f_prioritysync: 'Todos os 100+ canais + sync prioritária', f_prioritysup: 'Suporte prioritário (resposta 2h)', f_onboarding: 'Chamada de integração personalizada', f_whitelabel: 'Opções white-label',
    plan_note: 'Teste grátis de 14 dias',
    ent_name: 'EMPRESARIAL', ent_price: 'Preço Personalizado', ent_desc: 'Para grandes propriedades e grupos hoteleiros.',
    ent_1: '✓ Mais de 150 quartos', ent_2: '✓ Mensagens IA ilimitadas', ent_3: '✓ Tudo do Growth', ent_4: '✓ Gestor de conta dedicado', ent_5: '✓ Integrações personalizadas', ent_6: '✓ Garantia SLA', ent_cta: 'Contacte-nos →',
    comp_feature: 'Recurso', comp_r1: 'Automação de mensagens com IA', comp_r2: 'Respostas IA em mais de 30 idiomas', comp_r4: 'Calendário visual de quartos', comp_r6: 'App móvel offline', comp_price: 'Preço inicial',
    cta_trial: 'Teste grátis de 14 dias', cta_cancel: 'Cancele quando quiser',
    foot_desc: 'Gestão hoteleira com IA para hotéis independentes em todo o mundo.',
    earlybird: '🔥 Early Bird', comp_expensive: 'caro em grande escala',
    comp_r3: 'Integração 100+ OTA', comp_r5: 'Vendas de transferes e tours', comp_r7: 'Formulários de visto PDF (auto)', comp_perlisting: 'Por anúncio',
    faq_back: '← Voltar ao início', faq_title: 'Perguntas Frequentes', faq_sub: 'Tudo o que precisa de saber sobre o Hostlio Pro. Não encontra uma resposta?', faq_contact: 'Contacte-nos', faq_cta: 'Teste Grátis →',
    faq_q1: 'O que é o Hostlio Pro?', faq_a1: 'O Hostlio Pro é uma plataforma de gestão hoteleira com IA para hotéis independentes, B&Bs boutique e hostels. Automatiza as mensagens com hóspedes em mais de 30 idiomas, sincroniza a sua disponibilidade em mais de 100 canais OTA via Channex e oferece um único painel para gerir a sua propriedade.',
    faq_q2: 'Quanto tempo demora a configuração?', faq_a2: 'A maioria dos hotéis fica operacional em cerca de 30 minutos. Liga os seus canais, importa os quartos e reservas e configura o seu assistente de IA — sem equipa de TI.',
    faq_q3: 'Que canais de reserva suportam?', faq_a3: 'Através da nossa integração Channex, o Hostlio Pro liga-se a mais de 100 OTAs incluindo Booking.com, Airbnb, Expedia, Agoda e Trip.com. A disponibilidade e as tarifas sincronizam em tempo real para evitar overbookings. Veja a nossa <a href="/channels.html" style="color:var(--orange);font-weight:600">lista completa de canais</a>.',
    faq_q4: 'Que idiomas a IA suporta?', faq_a4: 'O assistente de IA responde aos hóspedes em mais de 30 idiomas automaticamente — deteta o idioma do hóspede e responde naturalmente, 24/7, sem esforço extra da sua parte.',
    faq_q5: 'Que canais de mensagens são suportados?', faq_a5: 'O Hostlio Pro gere as mensagens dos hóspedes em caixas OTA (Booking.com, Airbnb), Email, o widget de chat do seu site e Telegram. São adicionados novos canais regularmente.',
    faq_q6: 'Quanto custa?', faq_a6: 'Os planos começam em $49/mês (Starter, normalmente $59) para até 10 quartos. Pro ($89/mo) adiciona todos os canais mais vendas de transferes e tours para até 50 quartos. Growth ($149/mo) cobre até 150 quartos com suporte prioritário.',
    faq_q7: 'Existe um teste grátis?', faq_a7: 'Sim — pode começar um teste grátis e explorar toda a plataforma antes de se comprometer. Sem pressão de cartão de crédito, cancele quando quiser.',
    faq_q8: 'Oferecem check-in online?', faq_a8: 'Sim. Os hóspedes podem completar o check-in online antes da chegada — fornecendo os seus dados e documentos de identidade/passaporte através de um formulário seguro. Pode rever e exportar esta informação a partir do seu painel.',
    faq_q9: 'Existe uma app móvel?', faq_a9: 'Sim, o Hostlio Pro inclui uma app móvel para gerir reservas, hóspedes, preços e mensagens em movimento — mesmo offline.',
    faq_q10: 'Posso cancelar quando quiser?', faq_a10: 'Com certeza. Não há contratos de longo prazo. Pode gerir ou cancelar a sua subscrição a qualquer momento a partir do portal de faturação.',
    plan_desc_starter: 'Perfeito para pequenos hotéis independentes a começar com a automação.',
    plan_desc_pro: 'A solução completa para hotéis movimentados em todos os canais.',
    plan_desc_growth: 'Expanda por várias propriedades com suporte de concierge.',
    foot_privacy: 'Política de Privacidade', foot_terms: 'Termos de Serviço',
  },
  fr: {
    nav_features: 'Fonctionnalités', nav_pricing: 'Tarifs', nav_demo: 'Démo', nav_dashboard: 'Aller au Tableau de bord', nav_getstarted: 'Commencer',
    hero_badge: 'Gestion Hôtelière par IA',
    hero_title_1: 'Votre Réception<br>par IA.',
    hero_title_2: '24/7, en plus de 30 langues.',
    hero_sub: 'Ne perdez plus de réservations à cause de messages sans réponse. Automatisez la communication client sur Booking.com, Airbnb, Email, Chat Web et Telegram — à partir de 49 $/mois.',
    hero_cta_trial: 'Essai Gratuit →', hero_cta_demo: 'Voir la Démo',
    pain_label: 'Problèmes', pain_title: 'Ça vous parle ?', pain_sub: 'Chaque hôtelier indépendant connaît ces problèmes. Nous avons créé Hostlio Pro pour tous les résoudre.',
    pain_1: '"Les clients écrivent à 3h du matin. Vous ratez le message. Ils réservent ailleurs."', pain_2: '"5 plateformes. 5 connexions. Des heures perdues chaque jour."', pain_3: '"Un mauvais clic. Double réservation. Clients mécontents."', pain_4: '"La basse saison frappe fort. Aucun outil pour remplir les chambres."',
    feat_label: 'Fonctionnalités', feat_title: 'Tout ce dont votre hôtel a besoin.<br>Rien d\'inutile.', feat_sub: 'Une plateforme simple et élégante qui remplace cinq outils différents.',
    feat_1_t: 'Messagerie par IA', feat_1_d: 'Répond en plus de 30 langues sur les OTA, Email, Chat Web et Telegram. 24/7 — sans lever le petit doigt.',
    feat_2_t: 'Calendrier des Chambres', feat_2_d: 'Glissez-déposez les réservations. Voyez chaque chambre en un coup d\'œil.',
    feat_3_t: 'Intégration 100+ OTA', feat_3_d: 'Booking.com, Airbnb, Expedia, Agoda, Trip.com et plus de 100 via Channex. Synchro en temps réel. Zéro surréservation.',
    feat_4_t: 'Formulaires de Visa PDF', feat_4_d: 'Générez automatiquement avec le logo de votre hôtel. Partagez instantanément au check-in.',
    feat_5_t: 'Transferts et Excursions', feat_5_d: 'Vendez des transferts aéroport automatiquement. Revenus supplémentaires, zéro effort.',
    feat_6_t: 'Application Mobile', feat_6_d: 'Gérez votre hôtel hors ligne. Fonctionne sans internet. Toujours dans votre poche.',
    how_label: 'Comment ça Marche', how_title: 'Opérationnel en 30 minutes', how_sub: 'Pas d\'équipe informatique. Pas de configuration complexe. Juste quatre étapes simples.',
    how_1_t: 'Connectez vos canaux', how_1_d: 'Reliez Booking.com, Airbnb, Expedia et plus de 100 en un clic. Vos réservations s\'importent automatiquement.',
    how_2_t: 'L\'IA gère les messages', how_2_d: 'Votre assistant IA répond à chaque client — dans sa langue — jour et nuit. Vous validez, ne répétez jamais.',
    how_3_t: 'Gérez depuis un tableau de bord', how_3_d: 'Voyez toutes les chambres, canaux et messages au même endroit. Gagnez plus de 3 heures par jour.',
    how_4_t: 'Augmentez vos revenus', how_4_d: 'Proposez transferts, excursions et extras automatiquement. Votre IA suggère des extras à chaque client.',
    price_label: 'Tarifs', price_title: 'Tarifs simples et transparents', price_sub: 'Pas de frais cachés. Pas de contrats longs. Annulez quand vous voulez.',
    comp_label: 'Comparaison', comp_title: 'Pourquoi les hôtels choisissent Hostlio Pro', comp_sub: 'Découvrez comment nous nous comparons aux logiciels hôteliers traditionnels.',
    cta_title: 'Prêt à automatiser votre hôtel ?',
    banner_earlybird: '🔥 Offre Early Bird — Limitée aux 50 prochains clients : 20% de réduction sur tous les forfaits !',
    trust_worldwide: 'La confiance des hôtels indépendants dans le monde entier', trust_label: 'La confiance des hôtels indépendants dans plus de 20 pays — se synchronise avec',
    plan_cta: 'Essai Gratuit', plan_cta_arrow: 'Essai Gratuit →',
    cta_sub: 'Rejoignez les hôtels indépendants qui économisent plus de 3 heures par jour avec Hostlio Pro.', cta_btn: 'Essai Gratuit →',
    foot_product: 'Produit', foot_company: 'Entreprise', foot_legal: 'Légal', foot_how: 'Comment ça Marche', foot_compare: 'Comparer', foot_about: 'À propos', foot_contact: 'Contact',
    stat_countries: '20+ Pays', stat_sync: 'Synchro 100+ Canaux', stat_overbook: 'Zéro surréservation garantie',
    f_1prop: '1 établissement', f_10rooms: "Jusqu'à 10 chambres", f_5kmsg: '5 000 messages IA/mois', f_otaemail: 'Messagerie OTA + Email', f_roomrack: 'Calendrier des Chambres', f_pdfvisa: 'Formulaires de Visa PDF',
    f_50rooms: "Jusqu'à 50 chambres", f_20kmsg: '20 000 messages IA/mois', f_allchan: 'Tous les canaux (100+ OTA)', f_allmsg: 'OTA + Email + Chat Web + Telegram', f_transfer: 'Ventes de transferts et excursions', f_mobile: 'Application Mobile',
    f_multiprop: 'Multi-établissement', f_150rooms: "Jusqu'à 150 chambres", f_50kmsg: '50 000 messages IA/mois', f_prioritysync: 'Tous les 100+ canaux + sync prioritaire', f_prioritysup: 'Support prioritaire (réponse 2h)', f_onboarding: "Appel d'intégration personnalisé", f_whitelabel: 'Options marque blanche',
    plan_note: 'Essai gratuit de 14 jours',
    ent_name: 'ENTREPRISE', ent_price: 'Tarif Personnalisé', ent_desc: 'Pour les grands établissements et groupes hôteliers.',
    ent_1: '✓ Plus de 150 chambres', ent_2: '✓ Messages IA illimités', ent_3: '✓ Tout de Growth', ent_4: '✓ Gestionnaire de compte dédié', ent_5: '✓ Intégrations personnalisées', ent_6: '✓ Garantie SLA', ent_cta: 'Contactez-nous →',
    comp_feature: 'Fonctionnalité', comp_r1: 'Automatisation des messages par IA', comp_r2: 'Réponses IA en plus de 30 langues', comp_r4: 'Calendrier visuel des chambres', comp_r6: 'Application mobile hors ligne', comp_price: 'Prix de départ',
    cta_trial: 'Essai gratuit de 14 jours', cta_cancel: 'Annulez quand vous voulez',
    foot_desc: 'Gestion hôtelière par IA pour les hôtels indépendants du monde entier.',
    earlybird: '🔥 Early Bird', comp_expensive: 'coûteux à grande échelle',
    comp_r3: 'Intégration 100+ OTA', comp_r5: 'Ventes de transferts et excursions', comp_r7: 'Formulaires de visa PDF (auto)', comp_perlisting: 'Par annonce',
    faq_back: '← Retour à l\'accueil', faq_title: 'Questions Fréquentes', faq_sub: "Tout ce que vous devez savoir sur Hostlio Pro. Vous ne trouvez pas de réponse ?", faq_contact: 'Contactez-nous', faq_cta: 'Essai Gratuit →',
    faq_q1: "Qu'est-ce que Hostlio Pro ?", faq_a1: 'Hostlio Pro est une plateforme de gestion hôtelière par IA pour les hôtels indépendants, B&B boutique et auberges. Elle automatise la messagerie client en plus de 30 langues, synchronise votre disponibilité sur plus de 100 canaux OTA via Channex et vous offre un tableau de bord unique pour gérer votre établissement.',
    faq_q2: 'Combien de temps prend la configuration ?', faq_a2: 'La plupart des hôtels sont opérationnels en environ 30 minutes. Vous connectez vos canaux, importez vos chambres et réservations et configurez votre assistant IA — sans équipe informatique.',
    faq_q3: 'Quels canaux de réservation prenez-vous en charge ?', faq_a3: 'Grâce à notre intégration Channex, Hostlio Pro se connecte à plus de 100 OTA dont Booking.com, Airbnb, Expedia, Agoda et Trip.com. La disponibilité et les tarifs se synchronisent en temps réel pour éviter les surréservations. Consultez notre <a href="/channels.html" style="color:var(--orange);font-weight:600">liste complète des canaux</a>.',
    faq_q4: 'Quelles langues l\'IA prend-elle en charge ?', faq_a4: 'L\'assistant IA répond aux clients en plus de 30 langues automatiquement — il détecte la langue du client et répond naturellement, 24/7, sans effort supplémentaire de votre part.',
    faq_q5: 'Quels canaux de messagerie sont pris en charge ?', faq_a5: 'Hostlio Pro gère les messages clients via les boîtes OTA (Booking.com, Airbnb), Email, le widget de chat de votre site et Telegram. De nouveaux canaux sont ajoutés régulièrement.',
    faq_q6: 'Combien ça coûte ?', faq_a6: 'Les forfaits commencent à 49 $/mois (Starter, normalement 59 $) pour jusqu\'à 10 chambres. Pro (89 $/mo) ajoute tous les canaux plus les ventes de transferts et excursions pour jusqu\'à 50 chambres. Growth (149 $/mo) couvre jusqu\'à 150 chambres avec support prioritaire.',
    faq_q7: 'Y a-t-il un essai gratuit ?', faq_a7: 'Oui — vous pouvez commencer un essai gratuit et explorer toute la plateforme avant de vous engager. Aucune pression de carte de crédit, annulez quand vous voulez.',
    faq_q8: 'Proposez-vous l\'enregistrement en ligne ?', faq_a8: 'Oui. Les clients peuvent effectuer l\'enregistrement en ligne avant l\'arrivée — en fournissant leurs informations et documents d\'identité/passeport via un formulaire sécurisé. Vous pouvez consulter et exporter ces informations depuis votre tableau de bord.',
    faq_q9: 'Y a-t-il une application mobile ?', faq_a9: 'Oui, Hostlio Pro inclut une application mobile pour gérer réservations, clients, tarifs et messages en déplacement — même hors ligne.',
    faq_q10: 'Puis-je annuler à tout moment ?', faq_a10: 'Absolument. Il n\'y a pas de contrats à long terme. Vous pouvez gérer ou annuler votre abonnement à tout moment depuis le portail de facturation.',
    plan_desc_starter: 'Parfait pour les petits hôtels indépendants qui débutent avec l\'automatisation.',
    plan_desc_pro: 'La solution complète pour les hôtels actifs sur tous les canaux.',
    plan_desc_growth: 'Développez-vous sur plusieurs établissements avec un support concierge.',
    foot_privacy: 'Politique de Confidentialité', foot_terms: 'Conditions de Service',
  },
};

const LANGS = [['en','EN'],['tr','TR'],['es','ES'],['it','IT'],['pt','PT'],['fr','FR']];

function getLang() {
  const saved = localStorage.getItem('hostlio_lang');
  if (saved && I18N[saved]) return saved;
  const browser = (navigator.language || 'en').slice(0, 2).toLowerCase();
  return I18N[browser] ? browser : 'en';
}

function applyLang(lang) {
  const dict = I18N[lang] || I18N.en;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.innerHTML = dict[key];
  });
  localStorage.setItem('hostlio_lang', lang);
  document.documentElement.lang = lang;
  document.querySelectorAll('.lang-btn').forEach(b => {
    b.classList.toggle('active', b.getAttribute('data-lang') === lang);
  });
}

function buildLangSwitcher() {
  const wrap = document.getElementById('lang-switcher');
  if (!wrap) return;
  wrap.innerHTML = LANGS.map(([code, label]) =>
    `<button class="lang-btn" data-lang="${code}">${label}</button>`).join('');
  wrap.querySelectorAll('.lang-btn').forEach(b => {
    b.addEventListener('click', () => applyLang(b.getAttribute('data-lang')));
  });
}

document.addEventListener('DOMContentLoaded', () => {
  buildLangSwitcher();
  applyLang(getLang());
});
