"""Güvenlik ve veri sayfası (6 dil) + Veri İşleme Sözleşmesi / DPA (yalnız İngilizce, esas metin).
Rapor: K5 (DPA) ve "Güçlendirme önerileri → Güvenlik ve veri sayfası"."""
import legal_v6 as LV
import ozellik_ekleri as FXM

S = {
 "en": dict(title="Security and Data Protection | Hostlio Pro", desc="How Hostlio Pro protects hotel and guest data: encryption, access control, subprocessors, data retention, GDPR, KVKK and our Data Processing Addendum.",
  h1="Security and data protection", lead="Hotels trust us with reservations, guest messages and identity document details. This page explains how we protect them, who processes them, and how you can sign our Data Processing Addendum.",
  cards=[("lock-simple","Encrypted everywhere","TLS in transit and encryption at rest for the database and file storage."),("users-three","Access by role and hotel","Each hotel only sees its own data; staff access follows roles you set, and important actions are kept in an activity log."),("shield-check","Audited providers","SOC 2 Type 2 database provider; card payments via Stripe (PCI DSS Level 1)."),("file-pdf","DPA ready","A Data Processing Addendum for GDPR, UK GDPR, KVKK and CCPA.")],
  sec=[("Where your data lives","Our database, authentication and server functions run on Supabase, with the database and file storage hosted in the EU (Ireland); the website and dashboard are hosted on Vercel. Some providers are in the United States; transfers from the EEA, the UK and Türkiye are covered by Standard Contractual Clauses or other lawful mechanisms."),
       ("Payments","Card details are entered into Stripe and never reach our servers. We only see the plan, billing period and payment status."),
       ("AI and guest messages","Lio sends guest message content to our AI provider only to draft a reply. Under its commercial terms, the provider does not use this content to train its models. You decide which topics Lio answers automatically and which need your approval. For Lio Suggestions, contact details, long numbers and guest names are masked before guest messages and reviews are analysed, and the results contain no personal names."),
       ("Online check-in data","Identity document details and digital signatures are treated as sensitive data and are visible only to staff whose role allows it. Signatures are deleted {sg} days after check-out; identity document details are deleted with your account at the latest. We do not store images of ID documents or passports: the machine-readable zone is read on the guest’s or your staff’s own device and only the extracted fields are sent."),
       ("Retention","Guest message content is anonymised {m} days after check-out (you can shorten this to {mn}); guest email, phone and booking notes are erased {g} days after check-out; guest profiles are anonymised after {pr} days without a stay; the activity log is kept {au} days. Full list in our Privacy Policy, section 7."),
       ("Your roles under GDPR and KVKK","For guest data your hotel is the controller and Hostlio Pro is the processor. Our Data Processing Addendum sets out these obligations and forms part of our Terms of Service.")],
  sp_h="Subprocessors", dpa_h="Data Processing Addendum", dpa_p="Our DPA applies automatically when you accept the Terms of Service. You can read and print it, or ask for a countersigned copy.", dpa_btn="Read the DPA", dpa_pdf="Download PDF",
  report_h="Report a security issue", report_p="If you find a vulnerability, email {e} with the details. Please do not access other customers’ data or disrupt the service while testing. We reply within two business days.",
  more="More detail in our <a href=\"{p}\">Privacy Policy</a> and <a href=\"{t}\">Terms of Service</a>."),
 "tr": dict(title="Güvenlik ve Veri Koruma | Hostlio Pro", desc="Hostlio Pro otel ve misafir verilerini nasıl korur: şifreleme, erişim kontrolü, alt işleyiciler, saklama süreleri, KVKK, GDPR ve Veri İşleme Sözleşmesi.",
  h1="Güvenlik ve veri koruma", lead="Oteller rezervasyonlarını, misafir mesajlarını ve kimlik bilgilerini bize emanet ediyor. Bu sayfa onları nasıl koruduğumuzu, kimlerin işlediğini ve Veri İşleme Sözleşmemizi (DPA) nasıl imzalayabileceğinizi anlatır.",
  cards=[("lock-simple","Her yerde şifreli","Aktarımda TLS; veritabanı ve dosya depolamada şifreleme."),("users-three","Role ve otele göre erişim","Her otel yalnız kendi verisini görür; personel erişimi belirlediğiniz rollere göre, önemli işlemler işlem geçmişinde tutulur."),("shield-check","Denetimli sağlayıcılar","SOC 2 Type 2 denetimli veritabanı; kart ödemeleri Stripe (PCI DSS Level 1) ile."),("file-pdf","DPA hazır","GDPR, UK GDPR, KVKK ve CCPA için Veri İşleme Sözleşmesi.")],
  sec=[("Verileriniz nerede","Veritabanı, kimlik doğrulama ve sunucu fonksiyonlarımız Supabase’te çalışır; veritabanı ve dosya depolama AB’de (İrlanda) barındırılır. Web sitesi ve panel Vercel’de çalışır. Bazı sağlayıcılar ABD’dedir; AEA, Birleşik Krallık ve Türkiye’den yapılan aktarımlar Standart Sözleşme Maddeleri veya diğer yasal araçlarla korunur."),
       ("Ödemeler","Kart bilgileri Stripe’a girilir ve sunucularımıza hiç ulaşmaz. Biz yalnızca planı, fatura dönemini ve ödeme durumunu görürüz."),
       ("Yapay zekâ ve misafir mesajları","Lio, misafir mesajının içeriğini yalnızca cevap taslağı hazırlamak için yapay zekâ sağlayıcımıza gönderir. Sağlayıcı, ticari şartları gereği bu içeriği modellerini eğitmekte kullanmaz. Lio’nun hangi konulara otomatik cevap vereceğine ve hangilerinin onay gerektireceğine siz karar verirsiniz. Lio Önerileri için misafir mesajları ve yorumlar incelenmeden önce iletişim bilgileri, uzun sayılar ve misafir adları maskelenir; sonuçlarda kişi adı yer almaz."),
       ("Online check-in verileri","Kimlik belgesi bilgileri ve dijital imzalar hassas veri olarak ele alınır ve yalnız rolü izin veren personele görünür. İmzalar çıkıştan {sg} gün sonra silinir; kimlik belgesi bilgileri en geç hesabınızla birlikte silinir. Kimlik ve pasaport görüntüsü saklamayız: makine okunabilir alan misafirin ya da personelinizin kendi cihazında okunur, yalnızca okunan alanlar gönderilir (KVKK İlke Kararı 2025/2120)."),
       ("Saklama","Misafir mesaj içerikleri çıkıştan {m} gün sonra anonimleştirilir ({mn} güne kadar kısaltabilirsiniz); misafirin e-postası, telefonu ve rezervasyon notları çıkıştan {g} gün sonra silinir; misafir profilleri {pr} gün konaklama olmazsa anonimleştirilir; işlem geçmişi {au} gün tutulur. Tam liste Gizlilik Politikamızın 7. bölümünde."),
       ("GDPR ve KVKK kapsamındaki roller","Misafir verilerinde otel veri sorumlusu, Hostlio Pro veri işleyendir. Bu yükümlülükler Veri İşleme Sözleşmemizde yer alır ve Kullanım Şartlarımızın parçasıdır.")],
  sp_h="Alt işleyiciler", dpa_h="Veri İşleme Sözleşmesi (DPA)", dpa_p="DPA, Kullanım Şartlarını kabul ettiğinizde otomatik olarak geçerli olur. Okuyup yazdırabilir veya karşı imzalı bir nüsha isteyebilirsiniz. Sözleşme metni İngilizcedir.", dpa_btn="DPA’yı okuyun", dpa_pdf="PDF indir",
  report_h="Güvenlik açığı bildirin", report_p="Bir güvenlik açığı bulursanız ayrıntıları {e} adresine yazın. Test ederken diğer müşterilerin verilerine erişmeyin ve hizmeti aksatmayın. İki iş günü içinde dönüş yaparız.",
  more="Ayrıntılar <a href=\"{p}\">Gizlilik Politikası</a> ve <a href=\"{t}\">Kullanım Şartları</a> sayfalarında."),
 "es": dict(title="Seguridad y protección de datos | Hostlio Pro", desc="Cómo protege Hostlio Pro los datos de hoteles y huéspedes: cifrado, control de acceso, subencargados, conservación, RGPD y nuestro acuerdo DPA.",
  h1="Seguridad y protección de datos", lead="Los hoteles nos confían reservas, mensajes de huéspedes y datos de documentos de identidad. Aquí explicamos cómo los protegemos, quién los trata y cómo firmar nuestro Acuerdo de tratamiento de datos (DPA).",
  cards=[("lock-simple","Cifrado en todo momento","TLS en tránsito y cifrado en reposo de la base de datos y los archivos."),("users-three","Acceso por función y hotel","Cada hotel solo ve sus datos; el acceso del personal sigue los roles que definas y las acciones importantes quedan en un registro de actividad."),("shield-check","Proveedores auditados","Base de datos con auditoría SOC 2 Tipo 2; pagos con tarjeta vía Stripe (PCI DSS Nivel 1)."),("file-pdf","DPA disponible","Acuerdo de tratamiento de datos para RGPD, UK GDPR, KVKK y CCPA.")],
  sec=[("Dónde están tus datos","La base de datos, la autenticación y las funciones de servidor funcionan en Supabase, con la base de datos y el almacenamiento de archivos alojados en la UE (Irlanda); el sitio y el panel se alojan en Vercel. Algunos proveedores están en EE. UU.; las transferencias desde el EEE, el Reino Unido y Turquía se protegen con Cláusulas Contractuales Tipo u otros mecanismos legales."),
       ("Pagos","Los datos de la tarjeta se introducen en Stripe y nunca llegan a nuestros servidores. Solo vemos el plan, el periodo de facturación y el estado del pago."),
       ("IA y mensajes de huéspedes","Lio envía el contenido del mensaje a nuestro proveedor de IA solo para redactar una respuesta. Según sus condiciones comerciales, el proveedor no lo usa para entrenar sus modelos. Tú decides qué temas responde Lio automáticamente y cuáles requieren tu aprobación. Para las Sugerencias de Lio, los datos de contacto, los números largos y los nombres de huéspedes se ocultan antes de analizar mensajes y reseñas, y los resultados no contienen nombres de personas."),
       ("Datos del check-in online","Los datos de documentos de identidad y las firmas digitales se tratan como datos sensibles y solo los ve el personal cuya función lo permite. Las firmas se eliminan {sg} días después de la salida; los datos de los documentos, como tarde, con tu cuenta. No guardamos imágenes de documentos ni pasaportes: la zona de lectura mecánica se lee en el dispositivo del huésped o de tu personal y solo se envían los datos extraídos."),
       ("Conservación","El contenido de los mensajes se anonimiza {m} días después de la salida (puedes acortarlo a {mn}); el email, el teléfono y las notas de la reserva se borran {g} días después de la salida; los perfiles de huéspedes se anonimizan tras {pr} días sin estancias; el registro de actividad se guarda {au} días. Lista completa en la sección 7 de nuestra Política de privacidad."),
       ("Funciones según el RGPD","Para los datos de huéspedes, tu hotel es el responsable y Hostlio Pro el encargado del tratamiento. Nuestro DPA recoge estas obligaciones y forma parte de las Condiciones del servicio.")],
  sp_h="Subencargados", dpa_h="Acuerdo de tratamiento de datos (DPA)", dpa_p="El DPA se aplica automáticamente al aceptar las Condiciones del servicio. Puedes leerlo e imprimirlo, o pedir una copia firmada. El texto del acuerdo está en inglés.", dpa_btn="Leer el DPA", dpa_pdf="Descargar PDF",
  report_h="Informar de un problema de seguridad", report_p="Si encuentras una vulnerabilidad, escribe a {e} con los detalles. No accedas a datos de otros clientes ni interrumpas el servicio al hacer pruebas. Respondemos en dos días laborables.",
  more="Más detalles en la <a href=\"{p}\">Política de privacidad</a> y las <a href=\"{t}\">Condiciones del servicio</a>."),
 "it": dict(title="Sicurezza e protezione dei dati | Hostlio Pro", desc="Come Hostlio Pro protegge i dati di hotel e ospiti: cifratura, controllo degli accessi, sub-responsabili, conservazione, GDPR e il nostro DPA.",
  h1="Sicurezza e protezione dei dati", lead="Gli hotel ci affidano prenotazioni, messaggi degli ospiti e dati dei documenti d’identità. Qui spieghiamo come li proteggiamo, chi li tratta e come firmare il nostro Accordo sul trattamento dei dati (DPA).",
  cards=[("lock-simple","Cifratura ovunque","TLS in transito e cifratura a riposo di database e file."),("users-three","Accesso per ruolo e hotel","Ogni hotel vede solo i propri dati; l’accesso dello staff segue i ruoli che imposti e le azioni importanti restano in un registro attività."),("shield-check","Fornitori certificati","Database con audit SOC 2 Type 2; pagamenti con carta tramite Stripe (PCI DSS Level 1)."),("file-pdf","DPA disponibile","Accordo sul trattamento dei dati per GDPR, UK GDPR, KVKK e CCPA.")],
  sec=[("Dove sono i tuoi dati","Database, autenticazione e funzioni server girano su Supabase, con database e archiviazione dei file ospitati nell’UE (Irlanda); sito e pannello sono ospitati su Vercel. Alcuni fornitori hanno sede negli USA; i trasferimenti da SEE, Regno Unito e Turchia sono tutelati da Clausole contrattuali tipo o altri strumenti legittimi."),
       ("Pagamenti","I dati della carta vengono inseriti in Stripe e non arrivano mai ai nostri server. Vediamo solo piano, periodo di fatturazione e stato del pagamento."),
       ("AI e messaggi degli ospiti","Lio invia il contenuto del messaggio al nostro fornitore di AI solo per preparare una risposta. Secondo le sue condizioni commerciali, il fornitore non lo usa per addestrare i modelli. Sei tu a decidere a quali argomenti Lio risponde da solo e quali richiedono la tua approvazione. Per i Suggerimenti di Lio, recapiti, numeri lunghi e nomi degli ospiti vengono mascherati prima di analizzare messaggi e recensioni, e i risultati non contengono nomi di persone."),
       ("Dati del check-in online","Dati dei documenti e firme digitali sono trattati come dati sensibili e sono visibili solo allo staff il cui ruolo lo consente. Le firme sono cancellate {sg} giorni dopo la partenza; i dati dei documenti al più tardi con il tuo account. Non conserviamo immagini di documenti o passaporti: la zona a lettura ottica viene letta sul dispositivo dell’ospite o del tuo staff e vengono inviati solo i dati estratti."),
       ("Conservazione","Il contenuto dei messaggi è anonimizzato {m} giorni dopo la partenza (puoi ridurlo a {mn}); email, telefono e note di prenotazione sono cancellati {g} giorni dopo la partenza; i profili ospite sono anonimizzati dopo {pr} giorni senza soggiorni; il registro attività è conservato {au} giorni. Elenco completo nella sezione 7 dell’Informativa sulla privacy."),
       ("Ruoli secondo il GDPR","Per i dati degli ospiti il titolare è il tuo hotel e Hostlio Pro è responsabile del trattamento. Il nostro DPA definisce questi obblighi e fa parte dei Termini di servizio.")],
  sp_h="Sub-responsabili", dpa_h="Accordo sul trattamento dei dati (DPA)", dpa_p="Il DPA si applica automaticamente quando accetti i Termini di servizio. Puoi leggerlo e stamparlo, o chiedere una copia controfirmata. Il testo dell’accordo è in inglese.", dpa_btn="Leggi il DPA", dpa_pdf="Scarica il PDF",
  report_h="Segnala un problema di sicurezza", report_p="Se trovi una vulnerabilità, scrivi a {e} con i dettagli. Durante i test non accedere ai dati di altri clienti e non interrompere il servizio. Rispondiamo entro due giorni lavorativi.",
  more="Maggiori dettagli nell’<a href=\"{p}\">Informativa sulla privacy</a> e nei <a href=\"{t}\">Termini di servizio</a>."),
 "pt": dict(title="Segurança e proteção de dados | Hostlio Pro", desc="Como o Hostlio Pro protege os dados de hotéis e hóspedes: criptografia, controle de acesso, suboperadores, retenção, LGPD, GDPR e nosso DPA.",
  h1="Segurança e proteção de dados", lead="Os hotéis nos confiam reservas, mensagens de hóspedes e dados de documentos de identidade. Aqui explicamos como protegemos esses dados, quem os trata e como assinar nosso Acordo de Tratamento de Dados (DPA).",
  cards=[("lock-simple","Criptografia em tudo","TLS em trânsito e criptografia em repouso do banco de dados e dos arquivos."),("users-three","Acesso por função e hotel","Cada hotel vê só os próprios dados; o acesso da equipe segue as funções que você definir e as ações importantes ficam em um registro de atividades."),("shield-check","Fornecedores auditados","Banco de dados com auditoria SOC 2 Tipo 2; pagamentos com cartão pela Stripe (PCI DSS Nível 1)."),("file-pdf","DPA pronto","Acordo de Tratamento de Dados para LGPD, GDPR, UK GDPR, KVKK e CCPA.")],
  sec=[("Onde ficam seus dados","Banco de dados, autenticação e funções de servidor rodam na Supabase, com o banco de dados e o armazenamento de arquivos hospedados na UE (Irlanda); o site e o painel ficam na Vercel. Alguns fornecedores estão nos EUA; as transferências internacionais são protegidas por Cláusulas Contratuais Padrão ou outros mecanismos legais."),
       ("Pagamentos","Os dados do cartão são digitados na Stripe e nunca chegam aos nossos servidores. Só vemos o plano, o período de cobrança e o status do pagamento."),
       ("IA e mensagens de hóspedes","O Lio envia o conteúdo da mensagem ao nosso fornecedor de IA apenas para redigir uma resposta. Pelos termos comerciais, o fornecedor não usa esse conteúdo para treinar modelos. Você decide quais assuntos o Lio responde sozinho e quais precisam da sua aprovação. Nas Sugestões do Lio, contatos, números longos e nomes de hóspedes são mascarados antes da análise de mensagens e avaliações, e os resultados não contêm nomes de pessoas."),
       ("Dados do check-in online","Dados de documentos e assinaturas digitais são tratados como dados sensíveis e só ficam visíveis para a equipe cuja função permite. As assinaturas são apagadas {sg} dias após o check-out; os dados dos documentos, no máximo, junto com a sua conta. Não armazenamos imagens de documentos ou passaportes: a zona de leitura mecânica é lida no aparelho do hóspede ou da sua equipe e só os dados extraídos são enviados."),
       ("Retenção","O conteúdo das mensagens é anonimizado {m} dias após o check-out (você pode reduzir para {mn}); e-mail, telefone e observações da reserva são apagados {g} dias após o check-out; perfis de hóspedes são anonimizados após {pr} dias sem estadias; o registro de atividades é guardado por {au} dias. Lista completa na seção 7 da Política de Privacidade."),
       ("Papéis na LGPD e no GDPR","Para os dados de hóspedes, o hotel é o controlador e o Hostlio Pro é o operador. Nosso DPA define essas obrigações e faz parte dos Termos de Serviço.")],
  sp_h="Suboperadores", dpa_h="Acordo de Tratamento de Dados (DPA)", dpa_p="O DPA vale automaticamente quando você aceita os Termos de Serviço. Você pode ler e imprimir, ou pedir uma cópia assinada. O texto do acordo está em inglês.", dpa_btn="Ler o DPA", dpa_pdf="Baixar PDF",
  report_h="Informe um problema de segurança", report_p="Se encontrar uma vulnerabilidade, escreva para {e} com os detalhes. Nos testes, não acesse dados de outros clientes nem interrompa o serviço. Respondemos em até dois dias úteis.",
  more="Mais detalhes na <a href=\"{p}\">Política de Privacidade</a> e nos <a href=\"{t}\">Termos de Serviço</a>."),
 "fr": dict(title="Sécurité et protection des données | Hostlio Pro", desc="Comment Hostlio Pro protège les données des hôtels et des clients : chiffrement, contrôle d’accès, sous-traitants, conservation, RGPD et notre DPA.",
  h1="Sécurité et protection des données", lead="Les hôtels nous confient leurs réservations, les messages de leurs clients et des données de pièces d’identité. Cette page explique comment nous les protégeons, qui les traite et comment signer notre Accord de traitement des données (DPA).",
  cards=[("lock-simple","Chiffré partout","TLS en transit et chiffrement au repos de la base de données et des fichiers."),("users-three","Accès par rôle et par hôtel","Chaque hôtel ne voit que ses données ; l’accès du personnel suit les rôles que vous définissez et les actions importantes sont consignées dans un journal d’activité."),("shield-check","Prestataires audités","Base de données auditée SOC 2 Type 2 ; paiements par carte via Stripe (PCI DSS niveau 1)."),("file-pdf","DPA disponible","Accord de traitement des données pour le RGPD, l’UK GDPR, la KVKK et le CCPA.")],
  sec=[("Où sont vos données","La base de données, l’authentification et les fonctions serveur tournent sur Supabase, la base de données et le stockage de fichiers étant hébergés dans l’UE (Irlande) ; le site et le tableau de bord sont hébergés sur Vercel. Certains prestataires sont aux États-Unis ; les transferts depuis l’EEE, le Royaume-Uni et la Turquie sont encadrés par les clauses contractuelles types ou d’autres mécanismes légaux."),
       ("Paiements","Les données de carte sont saisies chez Stripe et n’atteignent jamais nos serveurs. Nous ne voyons que le forfait, la période de facturation et le statut du paiement."),
       ("IA et messages clients","Lio transmet le contenu du message à notre fournisseur d’IA uniquement pour préparer une réponse. Selon ses conditions commerciales, le fournisseur ne l’utilise pas pour entraîner ses modèles. Vous choisissez les sujets auxquels Lio répond seul et ceux qui nécessitent votre validation. Pour les Suggestions de Lio, les coordonnées, les numéros longs et les noms des clients sont masqués avant l’analyse des messages et des avis, et les résultats ne contiennent aucun nom de personne."),
       ("Données du check-in en ligne","Les données des pièces d’identité et les signatures électroniques sont traitées comme des données sensibles, visibles uniquement par le personnel dont le rôle le permet. Les signatures sont supprimées {sg} jours après le départ ; les données des pièces d’identité au plus tard avec votre compte. Nous ne conservons aucune image de pièce d’identité ni de passeport : la bande de lecture automatique est lue sur l’appareil du client ou de votre personnel et seules les données extraites sont envoyées."),
       ("Conservation","Le contenu des messages est anonymisé {m} jours après le départ (vous pouvez réduire ce délai à {mn}) ; l’e-mail, le téléphone et les notes de réservation sont effacés {g} jours après le départ ; les fiches clients sont anonymisées après {pr} jours sans séjour ; le journal d’activité est conservé {au} jours. Liste complète à la section 7 de notre Politique de confidentialité."),
       ("Rôles au sens du RGPD","Pour les données des clients, votre hôtel est responsable du traitement et Hostlio Pro sous-traitant. Notre DPA fixe ces obligations et fait partie des Conditions d’utilisation.")],
  sp_h="Sous-traitants", dpa_h="Accord de traitement des données (DPA)", dpa_p="Le DPA s’applique automatiquement dès que vous acceptez les Conditions d’utilisation. Vous pouvez le lire et l’imprimer, ou demander un exemplaire contresigné. Le texte de l’accord est en anglais.", dpa_btn="Lire le DPA", dpa_pdf="Télécharger le PDF",
  report_h="Signaler un problème de sécurité", report_p="Si vous découvrez une vulnérabilité, écrivez à {e} en détaillant le problème. Pendant vos tests, n’accédez pas aux données d’autres clients et ne perturbez pas le service. Nous répondons sous deux jours ouvrés.",
  more="Plus de détails dans la <a href=\"{p}\">Politique de confidentialité</a> et les <a href=\"{t}\">Conditions d’utilisation</a>."),
}
DPA_PDF = "/assets/legal/hostlio-pro-dpa.pdf"

# Q10 (axe heading-order): kart ve ayrıntı gruplarının görsel olarak gizli H2 başlıkları
SEC_H = {"tr": ("Öne çıkan önlemler", "Ayrıntılar"), "en": ("Key safeguards", "Details"), "es": ("Medidas principales", "Detalles"),
         "it": ("Misure principali", "Dettagli"), "pt": ("Principais medidas", "Detalhes"), "fr": ("Mesures principales", "Détails")}

def security_page(L, build):
    s = S[L]; R = LV.RETENTION; url = build.url; icon = build.icon
    e = f'<a href="mailto:{build.EMAIL}">{build.EMAIL}</a>'
    cards = "".join(f'<div class="sec-card"><span class="mi">{icon(i)}</span><h3>{t}</h3><p>{d}</p></div>' for i, t, d in s["cards"])
    rows = "".join(f'<div class="row"><h3>{h}</h3><div><p>{p.format(m=R["msg_default_days"], g=R["guest_contact_days"], d=R["deletion_days"], mn=R["msg_min_days"], pr=R["guest_profile_days"], sg=R["signature_days"], au=R["audit_days"])}</p></div></div>' for h, p in s["sec"] + FXM.FX[L]["sec"])
    pdf = f'{build.btn(s["dpa_pdf"], DPA_PDF, "ghost", " download")}' if (build.ROOT / ("src" + DPA_PDF)).exists() else ""
    body = f'''<section class="page-hero"><div class="wrap"><h1>{s["h1"]}</h1><p class="lead">{s["lead"]}</p>{LV.taslak_serit(L)}</div></section>
<section style="padding-top:0" aria-labelledby="sec-cards-h"><div class="wrap"><h2 id="sec-cards-h" class="sr-only">{SEC_H[L][0]}</h2><div class="sec-cards">{cards}</div></div></section>
<section class="rule" aria-labelledby="sec-rows-h"><div class="wrap rows"><h2 id="sec-rows-h" class="sr-only">{SEC_H[L][1]}</h2>{rows}</div></section>
<section class="rule" aria-labelledby="sp-h"><div class="wrap prose"><h2 id="sp-h">{s["sp_h"]}</h2>{LV.sp_table(L)}</div></section>
<section class="rule" aria-labelledby="dpa-h"><div class="wrap prose"><h2 id="dpa-h">{s["dpa_h"]}</h2><p>{s["dpa_p"]}</p><div class="cta-row">{build.btn(s["dpa_btn"], url("dpa","en"))}{pdf}</div>
<h2>{s["report_h"]}</h2><p>{s["report_p"].format(e=e)}</p><p class="small muted">{s["more"].format(p=url("privacy",L), t=url("terms",L))}</p></div></section>'''
    return {"key": "security", "title": s["title"], "desc": s["desc"], "trail": [(s["h1"], url("security", L))], "body": body, "modified": LV.LEGAL_ISO}

def dpa_page(build):
    url = build.url; E = build.EMAIL; R = LV.RETENTION; ul = LV._ul
    rows = "".join(f"<tr><th scope=\"row\">{n}</th><td>{loc}</td><td>{LV.SP_PURPOSE['en'][k]}</td></tr>" for n, loc, k in LV.SUBPROCESSORS)
    body = f'''<section class="page-hero"><div class="wrap"><h1>Data Processing Addendum</h1><p class="meta">Version 1.1 (draft) · Effective <time datetime="{LV.LEGAL_ISO}">{LV.LEGAL_DATE["en"]}</time> · Loti Members LLC, 2108 N ST STE N, Sacramento, CA 95816, USA</p>
{LV.taslak_serit("en")}<p class="no-print"><button type="button" class="btn btn-ghost" data-print>Print or save as PDF</button></p></div></section>
<section style="padding-top:0"><div class="wrap prose dpa">
<p>This Data Processing Addendum (“DPA”) forms part of the <a href="{url("terms","en")}">Terms of Service</a> between Loti Members LLC, operator of Hostlio Pro (“Processor”, “we”), and the customer that has accepted them (“Controller”, “you”). It applies to personal data of your guests and staff that we process on your behalf when providing Hostlio Pro (“Customer Personal Data”). It takes effect when you accept the Terms of Service. A countersigned copy is available on request from {E}.</p>
<h2>1. Definitions</h2><p>“Data Protection Law” means all laws that apply to the processing of Customer Personal Data, including the EU General Data Protection Regulation 2016/679 (“GDPR”), the UK GDPR and Data Protection Act 2018, Turkish Law No. 6698 on the Protection of Personal Data (“KVKK”), Brazil’s LGPD and the California Consumer Privacy Act as amended (“CCPA”). “Controller”, “processor”, “data subject”, “personal data breach” and “processing” have the meanings given in the GDPR. “Subprocessor” means a third party we engage to process Customer Personal Data.</p>
<h2>2. Roles and instructions</h2><p>You are the controller and we are the processor (and, under the CCPA, your service provider). We process Customer Personal Data only on your documented instructions, which are these Terms, this DPA and your use and configuration of Hostlio Pro, unless the law requires otherwise; in that case we will inform you first unless the law prohibits it. We will tell you if we believe an instruction infringes Data Protection Law. You are responsible for the lawfulness of the processing, including informing guests and having a legal basis.</p>
<h2>3. Confidentiality</h2><p>Everyone we authorise to process Customer Personal Data is bound by confidentiality obligations.</p>
<h2>4. Security</h2><p>We implement the technical and organisational measures in Annex 2 and keep them appropriate to the risk. We may update them as long as the overall level of protection does not decrease.</p>
<h2>5. Subprocessors</h2><p>You give general authorisation for us to use subprocessors. The current list is in Annex 3 and on our <a href="{url("security","en")}">Security and data</a> page. We will notify you by email or in the dashboard at least 30 days before adding or replacing a subprocessor; you may object on reasonable data-protection grounds, and if we cannot resolve the objection you may terminate the affected service and receive a pro-rata refund of prepaid fees for it. We impose data-protection obligations on each subprocessor that are no less protective than this DPA and remain responsible for their performance.</p>
<h2>6. Data subject requests</h2><p>Taking into account the nature of the processing, we help you respond to requests from data subjects (access, correction, deletion, restriction, portability, objection), mainly through the features of the dashboard. If we receive a request directly, we will pass it to you without undue delay and will not respond ourselves unless you instruct us to.</p>
<h2>7. Personal data breaches</h2><p>We will notify you without undue delay, and in any case within 48 hours, after becoming aware of a personal data breach affecting Customer Personal Data. The notice will describe the breach, the data and data subjects concerned, likely consequences and the measures taken, as far as that information is available.</p>
<h2>8. Assistance</h2><p>We give reasonable assistance with data protection impact assessments and prior consultations with supervisory authorities, taking into account the information available to us.</p>
<h2>9. Deletion and return</h2><p>You can export your data while your account is active. {LV.DPA_DELETION} During the subscription, Customer Personal Data is deleted or anonymised automatically on the schedule in section 7 of our <a href="{url("privacy","en")}">Privacy Policy</a>: among others, guest message content {R["msg_default_days"]} days after check-out (you can shorten this to {R["msg_min_days"]} days), guest email, phone and booking notes {R["guest_contact_days"]} days after check-out, guest signatures {R["signature_days"]} days after check-out, inactive guest profiles after {R["guest_profile_days"]} days and activity log entries after {R["audit_days"]} days.</p>
<h2>10. Audits</h2><p>We make available the information reasonably necessary to demonstrate compliance with this DPA, including our subprocessors’ security reports where they allow it. If that is not sufficient, you may carry out an audit once a year, with 30 days’ notice, during business hours, at your cost and under confidentiality.</p>
<h2>11. International transfers</h2><p>Where Customer Personal Data is transferred from the EEA, Switzerland, the UK or Türkiye to a country without an adequacy decision, the parties agree that the Standard Contractual Clauses adopted by Commission Implementing Decision (EU) 2021/914 (Module 2, controller to processor) are incorporated by reference, with the UK International Data Transfer Addendum and the standard contracts published under KVKK Article 9 where applicable. For the Clauses: Clause 7 (docking) applies; Clause 9 option 2 (general authorisation) applies with the notice period in section 5; the optional wording in Clause 11 does not apply; Clauses 17 and 18 are governed by and subject to the courts of Ireland; Annexes I and II are Annex 1 and Annex 2 of this DPA.</p>
<h2>12. CCPA</h2><p>We will not sell or share Customer Personal Data, retain, use or disclose it for any purpose other than providing the service, or combine it with personal data we receive from others, except as the CCPA permits.</p>
<h2>13. Liability and precedence</h2><p>Each party’s liability under this DPA is subject to the limitations in the Terms of Service, except where Data Protection Law does not allow this. If this DPA conflicts with the Terms, this DPA prevails for the processing of Customer Personal Data; the Standard Contractual Clauses prevail over both.</p>
<h2>Annex 1 — Details of processing</h2>
{ul(["<strong>Subject matter and duration:</strong> providing Hostlio Pro for the term of your subscription and until deletion under section 9",
     "<strong>Nature and purpose:</strong> hosting and storage; syncing availability, rates and reservations with sales channels; sending and receiving guest messages on WhatsApp and OTA inboxes; drafting replies to guest messages and OTA reviews with AI (review replies are sent only after your approval); translating your message templates; Lio Suggestions, including AI analysis of guest messages and reviews for recurring themes after contact details, long numbers and guest names are masked; analytics and weekly and monthly report emails with aggregated figures; staff accounts with roles and an activity log; online check-in, including reading the identity document’s machine-readable zone on the guest’s or your staff’s device; emails to guests that you enable (such as check-in links); push notifications to your staff’s Hostlio Pro mobile app (iOS and Android); support",
     "<strong>Data subjects:</strong> your guests and their companions; authors of reviews on connected channels; your staff and users of the dashboard",
     "<strong>Categories of data:</strong> names, contact details (phone, email), reservation details (dates, room, price, channel), message content, preferences and requests; for online check-in, identity document details (name, document number or, for Turkish ID cards, the T.C. identity number, nationality, date of birth and expiry date) and digital signatures, with no images of identity documents collected or stored; for users of the mobile app, device push notification tokens and app instance identifiers; OTA reviews (text, ratings, reviewer name); for staff, name, email address, role, property access and activity log entries (action, time, app used and an IP address shortened to /24 for IPv4 or /48 for IPv6)",
     "<strong>Special categories:</strong> none intended. Identity document details and signatures are handled as sensitive data. Please do not ask guests to send health or other special-category data through Hostlio Pro",
     "<strong>Frequency:</strong> continuous"])}
<h2>Annex 2 — Technical and organisational measures</h2>
{ul(["Encryption in transit (TLS 1.2+) and at rest for databases and file storage",
     "Logical separation of each customer’s data and row-level access rules; staff access by role and property, with an activity log that cannot be edited and is kept for 365 days",
     "Authentication for all dashboard users; passwords stored as salted hashes by our authentication provider",
     "Least-privilege access for our personnel; production access limited to those who need it",
     "Payment card data handled only by Stripe (PCI DSS Level 1); no card data on our systems",
     "Managed infrastructure with automated backups and provider-level physical security (SOC 2 Type 2 audited database provider)",
     "Logging of security-relevant events and monitoring for abuse; fraud controls at signup",
     "Automatic retention schedules: anonymisation of guest message content, erasure of guest contact data, deletion of check-in signatures and of old activity log and notification entries",
     "Automatic masking of email addresses, phone numbers, web links, long numbers and guest names before guest texts are analysed for Lio Suggestions; AI results checked to contain no personal names or contact details",
     "Vendor review and written data-protection terms with each subprocessor",
     "Incident response process with customer notification as set out in section 7"])}
<h2>Annex 3 — Subprocessors</h2>
<div class="table-wrap"><table><thead><tr><th>Subprocessor</th><th>Location</th><th>Purpose</th></tr></thead><tbody>{rows}</tbody></table></div>
<p class="small muted">Planned: Twilio Inc. (WhatsApp numbers and messaging billing) and Twilio SendGrid (receiving guest emails for a planned email channel). They will be added with notice under section 5 before they process Customer Personal Data.</p>
<h2>Signatures</h2><p>Accepted electronically by the Controller when accepting the Terms of Service. For a countersigned copy, email {E} with your company name, address and the name of your signatory.</p>
</div></section>'''
    return {"key": "dpa", "title": "Data Processing Addendum (DPA) | Hostlio Pro",
            "desc": "Hostlio Pro Data Processing Addendum for hotels: GDPR, UK GDPR, KVKK and CCPA terms, security measures, subprocessors and international transfers.",
            "trail": [("Data Processing Addendum", url("dpa", "en"))], "body": body, "no_final": True, "modified": LV.LEGAL_ISO, "updated_txt": LV.LEGAL_DATE["en"]}
