s=open('/tmp/home_tr.py').read()
R=[
('("ai","sparkle","t-lilac","AI asistan Lio","Misafir mesajlarına 30+ dilde yanıt")','("ai","sparkle","t-lilac","Lio AI assistant","Guest replies in 30+ languages")'),
('("channel","arrows-left-right","t-mint","Kanal yöneticisi","100+ OTA ile anlık senkron")','("channel","arrows-left-right","t-mint","Channel manager","Real-time sync with 100+ OTAs")'),
('("rack","calendar-dots","t-sky","Oda rafı","Sürükle-bırak rezervasyon takvimi")','("rack","calendar-dots","t-sky","Room rack","Drag-and-drop reservation calendar")'),
('("checkin","identification-card","t-peach","Online check-in","Kimlik ve imza varıştan önce")','("checkin","identification-card","t-peach","Online check-in","ID and signature before arrival")'),
('("upsell","van","t-sand","Transfer ve tur","Mesajlaşırken ek gelir")','("upsell","van","t-sand","Transfers and tours","Extra revenue while you chat")'),
('("mobile","device-mobile","t-lilac","Mobil uygulama","Otel dışından yönetim")','("mobile","device-mobile","t-lilac","Mobile app","Run the hotel from anywhere")'),
('name="ilgi"','name="interest"'),
('Gelen kutusu<span>12 açık konuşma</span>','Inbox<span>12 open conversations</span>'),
("Çeviri: Check-in 14:00'te, bavullarınızı hemen alabiliriz.","Translation: Check-in is from 2 pm, we can hold your luggage."),
('<span class="pill">Senkron</span>','<span class="pill">In sync</span>'),
('Bağlı kanallar<span>Son senkron: şimdi</span>','Connected channels<span>Last sync: just now</span>'),
('Online check-in<span>Oda 202</span>','Online check-in<span>Room 202</span>'),
('<span>Ad soyad</span><div>Keiko Sato</div></div><div class="field"><span>Uyruk</span><div>Japonya</div></div>','<span>Full name</span><div>Keiko Sato</div></div><div class="field"><span>Nationality</span><div>Japan</div></div>'),
('<span>Refakatçi</span><div>1 misafir eklendi</div></div><div class="field"><span>İmza</span>','<span>Companions</span><div>1 guest added</div></div><div class="field"><span>Signature</span>'),
('<h1>Bağımsız oteller için <em class="hl">yapay zekâ</em> destekli otel yazılımı</h1>','<h1><em class="hl">AI-powered</em> hotel software for independent hotels</h1>'),
('Rezervasyonlar, 100+ satış kanalı ve misafir mesajları tek panelde. Lio misafirlerinize 30+ dilde, gece gündüz cevap verir.','Reservations, 100+ sales channels and guest messages in one place. Lio answers your guests in 30+ languages, day and night.'),
('btn("Ücretsiz dene", SIGNUP_URL)','btn("Try it free", SIGNUP_URL)'),('btn("Demo iste", U("contact"), "ghost")','btn("Book a demo", U("contact"), "ghost")'),
('<span>Channex ile bağlı:</span>','<span>Connected through Channex:</span>'),('<span>ve 100+ kanal</span>','<span>and 100+ more</span>'),
('<h2>Neyle başlamak istersiniz?</h2><p>Seçimlerinize göre hesabınızı hazırlayalım.</p>','<h2>What would you like to start with?</h2><p>Pick what matters and we set up your account around it.</p>'),
('data-none="İstediğiniz kadar seçebilirsiniz." data-some="{{n}} modül seçildi, 7 gün ücretsiz deneyin.">İstediğiniz kadar seçebilirsiniz.','data-none="Pick as many as you like." data-some="{{n}} selected, try them free for 7 days.">Pick as many as you like.'),
('Başla<span class="bi">','Get started<span class="bi">'),
('<h2>Otelinizin gününü <em class="hl">tek ekrandan</em> yönetin</h2><p>Misafir mesajı, rezervasyon, kanal ve check-in birbirine bağlı çalışır.</p>','<h2>Run your hotel\'s whole day <em class="hl">from one screen</em></h2><p>Guest messages, reservations, channels and check-in work together.</p>'),
('aria-label="Ürün turu"','aria-label="Product tour"'),
('Mesajlar</button>','Messages</button>'),('Takvim</button>','Calendar</button>'),('Kanallar</button>','Channels</button>'),
('<h3>Tüm misafir mesajları tek gelen kutusunda</h3><p>WhatsApp, e-posta, web sohbet, Telegram ve OTA mesajları bir arada. Lio otelinizin bilgileriyle cevaplar, siz sadece gerekeni görürsünüz.</p>{chk(["30+ dilde otomatik yanıt","Her mesajın yanında rezervasyon bilgisi","Emin olmadığı soruyu size devreder"])}{more("ai","Lio nasıl çalışır")}',
 '<h3>Every guest message in one inbox</h3><p>WhatsApp, email, web chat, Telegram and OTA messages together. Lio answers with your hotel\'s information, and you only see what needs you.</p>{chk(["Automatic replies in 30+ languages","Reservation details beside every message","Hands over what it isn\'t sure about"])}{more("ai","How Lio works")}'),
('<h3>Oda rafında haftanın tamamı</h3><p>Her rezervasyonu kanal rengiyle görün. Oda değiştirmek, konaklamayı uzatmak ya da blokaj koymak tek hareket.</p>{chk(["Sürükle-bırak oda değişikliği","Kanal renkleriyle rezervasyonlar","Web ve iOS\'ta aynı takvim"])}{more("features","Tüm özellikler")}',
 '<h3>Your whole week on the room rack</h3><p>See every booking in its channel colour. Moving rooms, extending stays or blocking dates takes one gesture.</p>{chk(["Drag-and-drop room moves","Bookings colour-coded by channel","The same calendar on web and iOS"])}{more("features","All features")}'),
('<h3>100+ kanal, tek müsaitlik</h3><p>Channex altyapısıyla çift yönlü senkron. Bir kanalda satılan oda diğerlerinde anında kapanır.</p>{chk(["Fiyat ve kısıtlamalar tek ekrandan","Yeni rezervasyon ve iptaller otomatik","Overbooking riski yok"])}{more("channel","Kanal yöneticisi")}',
 '<h3>100+ channels, one availability</h3><p>Two-way sync through Channex. A room sold on one channel closes on the others instantly.</p>{chk(["Rates and restrictions from one screen","New bookings and cancellations flow in","No overbooking risk"])}{more("channel","Channel manager")}'),
('<h3>Check-in varıştan önce biter</h3><p>Misafir güvenli bağlantıdan kimlik bilgilerini, refakatçilerini ve imzasını telefonundan gönderir.</p>{chk(["Uygulama indirmeden, tarayıcıda","Refakatçi misafirler tek formda","Dijital imza ve açık rıza"])}{more("checkin","Online check-in")}',
 '<h3>Check-in is done before arrival</h3><p>Guests send ID details, companions and a signature from their phone through a secure link.</p>{chk(["In the browser, no app download","Companions in a single form","Digital signature and consent"])}{more("checkin","Online check-in")}'),
("<h2>Rezervasyondan check&#8209;out'a, <em class=\"hl\">her adımda</em> Hostlio</h2>","<h2>From booking to check&#8209;out, Hostlio <em class=\"hl\">at every step</em></h2>"),
('alt="Ahşap panelli, loş ışıklı otel lobisi"','alt="Hotel lobby with wood panelling and warm light"'),
('<span>Oda 202 satıldı<small>Booking.com, 21:40</small></span>','<span>Room 202 sold<small>Booking.com, 21:40</small></span>'),
("{icon(\"check\")}Airbnb ve Expedia'da kapandı","{icon(\"check\")}Closed on Airbnb and Expedia"),
('<h3>Çift rezervasyona son</h3><p>Bir kanalda satılan oda, diğer tüm kanallarda anında kapanır.</p>','<h3>No more double bookings</h3><p>A room sold on one channel closes on every other channel instantly.</p>'),
('alt="Masa lambası ve yatağı olan butik otel odası"','alt="Boutique hotel room with a desk lamp and bed"'),
('<small>Misafir, 01:18</small>','<small>Guest, 01:18</small>'),('<small>Lio, 4 sn</small>','<small>Lio, 4 sec</small>'),
("<h3>Hiçbir soru sabaha kalmaz</h3><p>Lio, WhatsApp'tan OTA'ya her kanaldaki soruyu misafirin dilinde yanıtlar.</p>","<h3>No question waits until morning</h3><p>Lio answers on every channel, from WhatsApp to OTAs, in the guest's language.</p>"),
('alt="Otel odasında dizüstü bilgisayarla çalışan işletmeci"','alt="Hotel owner working on a laptop in a guest room"'),
('<span>Havalimanı transferi satıldı<small>+35 €</small></span>','<span>Airport transfer sold<small>+€35</small></span>'),
('{icon("identification-card")}Check-in formu tamamlandı</span>','{icon("identification-card")}Check-in form completed</span>'),
('<h3>Resepsiyon cebinizde</h3><p>Rezervasyon, satış ve check-in; otelde olmasanız da elinizin altında.</p>','<h3>The front desk in your pocket</h3><p>Bookings, sales and check-ins at hand, even when you\'re away from the hotel.</p>'),
('<h2>Otelinizin büyüklüğüne göre plan</h2><p>Sabit aylık ücret, uzun süreli sözleşme yok. Tüm planlar 7 gün ücretsiz.</p>','<h2>A plan for your hotel\'s size</h2><p>A flat monthly fee, no long-term contract. Every plan is free for 7 days.</p>'),
('İlk 50 müşteriye %20 indirim, abonelik boyunca sabit','20% off for the first 50 customers, locked in for life'),
('Fiyatlara vergi dahil değildir. <a href="{U("pricing")}">Planları detaylı karşılaştırın</a>.','Prices exclude taxes. <a href="{U("pricing")}">Compare plans in detail</a>.'),
('Bir otelin ihtiyacı olan her şey, <em class="hl">tek çatı altında</em>','Everything a hotel needs, <em class="hl">under one roof</em>'),
('Dağıtım{icon("plus","pl")}</summary><div class="body"><ul><li>100+ OTA ile kanal yöneticisi (Channex)</li><li>Fiyat, minimum konaklama ve satış kapatma</li><li>Google Hotels bağlantısı</li></ul><a href="{U("channel")}">Kanal yöneticisini inceleyin</a>',
 'Distribution{icon("plus","pl")}</summary><div class="body"><ul><li>Channel manager for 100+ OTAs (Channex)</li><li>Rates, minimum stays and stop-sells</li><li>Google Hotels connection</li></ul><a href="{U("channel")}">Explore the channel manager</a>'),
('Misafir iletişimi{icon("plus","pl")}</summary><div class="body"><ul><li>AI asistan Lio, 30+ dil</li><li>WhatsApp, e-posta, web sohbet, Telegram ve OTA mesajları tek kutuda</li><li>Manuel cevaplarda otomatik çeviri</li></ul><a href="{U("ai")}">Lio hakkında</a>',
 'Guest communication{icon("plus","pl")}</summary><div class="body"><ul><li>Lio AI assistant, 30+ languages</li><li>WhatsApp, email, web chat, Telegram and OTA messages in one inbox</li><li>Automatic translation for manual replies</li></ul><a href="{U("ai")}">About Lio</a>'),
('Resepsiyon{icon("plus","pl")}</summary><div class="body"><ul><li>Sürükle-bırak oda rafı</li><li>Online check-in, refakatçiler ve dijital imza</li><li>Çevrimdışı da çalışan iOS uygulaması</li></ul>',
 'Front desk{icon("plus","pl")}</summary><div class="body"><ul><li>Drag-and-drop room rack</li><li>Online check-in, companions and digital signature</li><li>iOS app that works offline</li></ul>'),
('Ek gelir{icon("plus","pl")}</summary><div class="body"><ul><li>Havalimanı transferi satışı</li><li>Şehir turu ve ek hizmetler</li><li>Lio teklifleri doğru anda sunar</li></ul><a href="{U("features")}">Tüm özellikler</a>',
 'Extra revenue{icon("plus","pl")}</summary><div class="body"><ul><li>Airport transfer sales</li><li>City tours and extras</li><li>Lio offers them at the right moment</li></ul><a href="{U("features")}">All features</a>'),
('Belgeler{icon("plus","pl")}</summary><div class="body"><ul><li>Otomatik PDF vize ve konaklama belgeleri</li><li>Misafir bilgilerini resmî bildirim için dışa aktarma</li><li>Talep üzerine misafir verisi silme</li></ul>',
 'Documents{icon("plus","pl")}</summary><div class="body"><ul><li>Automatic PDF visa and accommodation letters</li><li>Guest data export for official registration</li><li>Guest data deletion on request</li></ul>'),
('alt="Pencere kenarında beyaz nevresimli, aydınlık otel odası"','alt="Bright hotel room with white bedding by the window"'),
('<span>Keiko Sato, Oda 202<small>Online check-in tamamlandı, imza alındı</small></span>','<span>Keiko Sato, Room 202<small>Online check-in done, signature received</small></span>'),
('<h2>Lio: resepsiyonunuzun <em class="hl">gece vardiyası</em></h2><p>Otelinizin bilgileriyle çalışan yapay zekâ asistanı. Misafire cevap verir, satış yapar, gerekeni size bırakır.</p>','<h2>Lio, your front desk\'s <em class="hl">night shift</em></h2><p>An AI assistant that works from your hotel\'s information. It answers guests, sells extras and leaves the rest to you.</p>'),
('<h3>Misafirin dilinde cevap</h3><p>Japonca soru Japonca, Arapça soru Arapça yanıtlanır. Siz yazışmayı Türkçe okursunuz.</p>','<h3>Replies in the guest\'s language</h3><p>A Japanese question gets a Japanese answer, an Arabic one an Arabic answer. You read the conversation in your own language.</p>'),
('<h3>Satış yapar</h3><p>Havalimanı transferi ve turu doğru anda önerir, talebi rezervasyona bağlar.</p>','<h3>Sells for you</h3><p>Offers airport transfers and tours at the right moment and attaches the request to the booking.</p>'),
('<h3>Gerekeni size bırakır</h3><p>İndirim, şikâyet ya da özel istek gibi karar gerektiren mesajları personele iletir.</p>','<h3>Knows when to hand over</h3><p>Messages that need a decision, like discounts, complaints or special requests, go to your staff.</p>'),
('<h3>Rezervasyonu tanır</h3><p>Hangi misafir, hangi oda, hangi tarih; her cevabı rezervasyon bilgisiyle verir.</p>','<h3>Knows the booking</h3><p>Which guest, which room, which dates: every reply uses the reservation details.</p>'),
('<h3>Her kanalda</h3><p>WhatsApp, e-posta, web sohbet, Telegram, Booking.com ve Airbnb mesajları.</p>','<h3>On every channel</h3><p>WhatsApp, email, web chat, Telegram, Booking.com and Airbnb messages.</p>'),
('btn("Lio\'yu inceleyin", U("ai"))','btn("Explore Lio", U("ai"))'),
("<p><strong>Kısaca Hostlio:</strong> 10 ila 150 odalı bağımsız oteller için bulut tabanlı bir PMS. Misafir iletişimini yapay zekâya devreder, OTA rezervasyonlarını tek takvimde toplar, check-in'i misafirin telefonuna taşır. Web'den ve iOS uygulamasından yönetilir, 20'den fazla ülkede kullanılır.</p>",
 "<p><strong>Hostlio in short:</strong> a cloud PMS for independent hotels with 10 to 150 rooms. It hands guest communication to AI, pulls OTA bookings into one calendar and moves check-in to the guest's phone. Managed from the web and an iOS app, used in 20+ countries.</p>"),
('<span>dilde misafir yanıtı</span>','<span>languages answered</span>'),('<span>OTA ve satış kanalı</span>','<span>OTAs and sales channels</span>'),('<span>ülkede bağımsız oteller</span>','<span>countries with Hostlio hotels</span>'),('<b class="num">7 gün</b><span>ücretsiz deneme, taahhüt yok</span>','<b class="num">7 days</b><span>free trial, no commitment</span>'),
('<h2>Yanınızda bir ekip var</h2>','<h2>A team behind you</h2>'),
('<h3>Aynı gün kurulum</h3><p>Oda tiplerini girin, kanalları bağlayın. Growth planında birebir kurulum görüşmesi dahil.</p>','<h3>Same-day setup</h3><p>Add room types and connect channels. Growth includes a one-to-one onboarding call.</p>'),
('<h3>Türkçe ve İngilizce destek</h3><p>Takıldığınız yerde ekibe <a href="mailto:{EMAIL}">{EMAIL}</a> adresinden ulaşın.</p>','<h3>Support in English and Turkish</h3><p>Stuck on something? Reach the team at <a href="mailto:{EMAIL}">{EMAIL}</a>.</p>'),
('<h3>Rehberler</h3><p>Otel yönetimi ve dağıtım üzerine <a href="{U("blog")}">blog yazıları</a> ve <a href="{U("faq")}">sık sorulan sorular</a>.</p>','<h3>Guides</h3><p><a href="{U("blog")}">Blog posts</a> on hotel management and distribution, plus <a href="{U("faq")}">frequently asked questions</a>.</p>'),
('"title":"Hostlio | Bağımsız Oteller için AI Destekli Otel Yönetim Yazılımı"','"title":"Hostlio | AI Hotel Management Software for Independent Hotels"'),
('"desc":"Otel yönetim yazılımı Hostlio: AI asistan Lio misafir mesajlarını 30+ dilde 7/24 yanıtlar, kanal yöneticisi 100+ OTA\'yı senkronize eder. 7 gün ücretsiz deneyin."','"desc":"Hostlio hotel management software: the Lio AI assistant answers guest messages 24/7 in 30+ languages, and the channel manager syncs 100+ OTAs. Free 7-day trial."'),
]
for a,b in R:
    assert a in s,a[:80]
    s=s.replace(a,b)
import re
print('leftover TR:',sorted(set(re.findall(r'[ğüşıöçĞÜŞİÖÇ]\w*',s)))[:40])
c=open('content_en.py').read()
a=c.index('def home():'); b=c.index('def ai():')
c=c[:a]+s+c[b:]
c=c.replace('''<a class="btn {"btn-primary" if pop else "btn-ghost"}" href="{SIGNUP_URL}?plan={p["id"]}">Try {p["name"]} free for 7 days</a>''','''{btn("Start with "+p["name"], SIGNUP_URL+"?plan="+p["id"], "primary" if pop else "ghost")}''')
c=c.replace("from build import url,","from build import btn, icon, logo, url,",1)
c=c.replace('<p class="small muted num">Early-bird price (regularly <s>${p["regular"]}</s>)</p>','<p class="small muted num" style="margin:0">Early-bird price (regularly <s>${p["regular"]}</s>)</p>')
open('content_en.py','w').write(c)
